#' BigQuery API Objects 
#' A data platform for customers to create, manage, share and query data.
#' 
#' Auto-generated code by googleAuthR::gar_create_api_objects
#'  at 2016-09-03 22:43:18
#' filename: testbq.R
#' api_json: da1
#' 
#' Objects for use by the functions created by googleAuthR::gar_create_api_skeleton
	
#' BigtableColumn Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param encoding [Optional] The encoding of the values when the type is not STRING
#' @param fieldName [Optional] If the qualifier is not a valid BigQuery field identifier i
#' @param onlyReadLatest [Optional] If this is set, only the latest version of value in this column are exposed
#' @param qualifierEncoded [Required] Qualifier of the column
#' @param qualifierString No description
#' @param type [Optional] The type to convert the value in cells of this column
#' 
#' @return BigtableColumn object
#' 
#' @family BigtableColumn functions
#' @export
BigtableColumn <- function(encoding = NULL,fieldName = NULL,onlyReadLatest = NULL,qualifierEncoded = NULL,qualifierString = NULL,type = NULL){
structure(list(`encoding` = encoding,`fieldName` = fieldName,`onlyReadLatest` = onlyReadLatest,`qualifierEncoded` = qualifierEncoded,`qualifierString` = qualifierString,`type` = type), class = 'gar_BigtableColumn')}
	
#' BigtableColumnFamily Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param columns [Optional] Lists of columns that should be exposed as individual fields as opposed to a list of (column name, value) pairs
#' @param encoding [Optional] The encoding of the values when the type is not STRING
#' @param familyId Identifier of the column family
#' @param onlyReadLatest [Optional] If this is set only the latest version of value are exposed for all columns in this column family
#' @param type [Optional] The type to convert the value in cells of this column family
#' 
#' @return BigtableColumnFamily object
#' 
#' @family BigtableColumnFamily functions
#' @export
BigtableColumnFamily <- function(columns = NULL,encoding = NULL,familyId = NULL,onlyReadLatest = NULL,type = NULL){
structure(list(`columns` = columns,`encoding` = encoding,`familyId` = familyId,`onlyReadLatest` = onlyReadLatest,`type` = type), class = 'gar_BigtableColumnFamily')}
	
#' BigtableOptions Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param columnFamilies [Optional] List of column families to expose in the table schema along with their types
#' @param ignoreUnspecifiedColumnFamilies [Optional] If field is true, then the column families that are not specified in columnFamilies list are not exposed in the table schema
#' @param readRowkeyAsString [Optional] If field is true, then the rowkey column families will be read and converted to string
#' 
#' @return BigtableOptions object
#' 
#' @family BigtableOptions functions
#' @export
BigtableOptions <- function(columnFamilies = NULL,ignoreUnspecifiedColumnFamilies = NULL,readRowkeyAsString = NULL){
structure(list(`columnFamilies` = columnFamilies,`ignoreUnspecifiedColumnFamilies` = ignoreUnspecifiedColumnFamilies,`readRowkeyAsString` = readRowkeyAsString), class = 'gar_BigtableOptions')}
	
#' CsvOptions Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param allowJaggedRows [Optional] Indicates if BigQuery should accept rows that are missing trailing optional columns
#' @param allowQuotedNewlines [Optional] Indicates if BigQuery should allow quoted data sections that contain newline characters in a CSV file
#' @param encoding [Optional] The character encoding of the data
#' @param fieldDelimiter [Optional] The separator for fields in a CSV file
#' @param quote [Optional] The value that is used to quote data sections in a CSV file
#' @param skipLeadingRows [Optional] The number of rows at the top of a CSV file that BigQuery will skip when reading the data
#' 
#' @return CsvOptions object
#' 
#' @family CsvOptions functions
#' @export
CsvOptions <- function(allowJaggedRows = NULL,allowQuotedNewlines = NULL,encoding = NULL,fieldDelimiter = NULL,quote = NULL,skipLeadingRows = NULL){
structure(list(`allowJaggedRows` = allowJaggedRows,`allowQuotedNewlines` = allowQuotedNewlines,`encoding` = encoding,`fieldDelimiter` = fieldDelimiter,
`quote` = """,`skipLeadingRows` = skipLeadingRows), class = 'gar_CsvOptions')}
	
#' Dataset Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param Dataset.access The \link{Dataset.access} object or list of objects
#' @param Dataset.labels The \link{Dataset.labels} object or list of objects
#' @param access [Optional] An array of objects that define dataset access for one or more entities
#' @param creationTime [Output-only] The time when this dataset was created, in milliseconds since the epoch
#' @param datasetReference [Required] A reference that identifies the dataset
#' @param defaultTableExpirationMs [Optional] The default lifetime of all tables in the dataset, in milliseconds
#' @param description [Optional] A user-friendly description of the dataset
#' @param etag [Output-only] A hash of the resource
#' @param friendlyName [Optional] A descriptive name for the dataset
#' @param id [Output-only] The fully-qualified unique name of the dataset in the format projectId:datasetId
#' @param labels [Experimental] The labels associated with this dataset
#' @param lastModifiedTime [Output-only] The date when this dataset or any of its tables was last modified, in milliseconds since the epoch
#' @param location [Experimental] The geographic location where the dataset should reside
#' @param selfLink [Output-only] A URL that can be used to access the resource again
#' 
#' @return Dataset object
#' 
#' @family Dataset functions
#' @export
Dataset <- function(Dataset.access = NULL,Dataset.labels = NULL,access = NULL,creationTime = NULL,datasetReference = NULL,defaultTableExpirationMs = NULL,description = NULL,etag = NULL,friendlyName = NULL,id = NULL,labels = NULL,lastModifiedTime = NULL,location = NULL,selfLink = NULL){
structure(list(`Dataset.access` = Dataset.access,`Dataset.labels` = Dataset.labels,`access` = access,`creationTime` = creationTime,`datasetReference` = datasetReference,`defaultTableExpirationMs` = defaultTableExpirationMs,`description` = description,`etag` = etag,`friendlyName` = friendlyName,`id` = id,`kind` = "bigquery#dataset",`labels` = labels,`lastModifiedTime` = lastModifiedTime,`location` = location,`selfLink` = selfLink), class = 'gar_Dataset')}
	
#' Dataset.access Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' 
#' 
#' @return Dataset.access object
#' 
#' @family Dataset functions
#' @export
Dataset.access <- function(){
list()
}
	
#' Dataset.labels Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' [Experimental] The labels associated with this dataset. You can use these to organize and group your datasets. You can set this property when inserting or updating a dataset. Label keys and values can be no longer than 63 characters, can only contain letters, numeric characters, underscores and dashes. International characters are allowed. Label values are optional. Label keys must start with a letter and must be unique within a dataset. Both keys and values are additionally constrained to be <= 128 bytes in size.
#' 
#' 
#' 
#' @return Dataset.labels object
#' 
#' @family Dataset functions
#' @export
Dataset.labels <- function(){
list()
}
	
#' DatasetList Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param DatasetList.datasets The \link{DatasetList.datasets} object or list of objects
#' @param DatasetList.datasets.labels The \link{DatasetList.datasets.labels} object or list of objects
#' @param datasets An array of the dataset resources in the project
#' @param etag A hash value of the results page
#' @param nextPageToken A token that can be used to request the next results page
#' 
#' @return DatasetList object
#' 
#' @family DatasetList functions
#' @export
DatasetList <- function(DatasetList.datasets = NULL,DatasetList.datasets.labels = NULL,datasets = NULL,etag = NULL,nextPageToken = NULL){
structure(list(`DatasetList.datasets` = DatasetList.datasets,`DatasetList.datasets.labels` = DatasetList.datasets.labels,`datasets` = datasets,`etag` = etag,`kind` = "bigquery#datasetList",`nextPageToken` = nextPageToken), class = 'gar_DatasetList')}
	
#' DatasetList.datasets Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param DatasetList.datasets.labels The \link{DatasetList.datasets.labels} object or list of objects
#' 
#' @return DatasetList.datasets object
#' 
#' @family DatasetList functions
#' @export
DatasetList.datasets <- function(DatasetList.datasets.labels = NULL){
structure(list(`DatasetList.datasets.labels` = DatasetList.datasets.labels), class = 'gar_DatasetList.datasets')}
	
#' DatasetList.datasets.labels Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' [Experimental] The labels associated with this dataset. You can use these to organize and group your datasets.
#' 
#' 
#' 
#' @return DatasetList.datasets.labels object
#' 
#' @family DatasetList functions
#' @export
DatasetList.datasets.labels <- function(){
list()
}
	
#' DatasetReference Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param datasetId [Required] A unique ID for this dataset, without the project name
#' @param projectId [Optional] The ID of the project containing this dataset
#' 
#' @return DatasetReference object
#' 
#' @family DatasetReference functions
#' @export
DatasetReference <- function(datasetId = NULL,projectId = NULL){
structure(list(`datasetId` = datasetId,`projectId` = projectId), class = 'gar_DatasetReference')}
	
#' ErrorProto Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param debugInfo Debugging information
#' @param location Specifies where the error occurred, if present
#' @param message A human-readable description of the error
#' @param reason A short error code that summarizes the error
#' 
#' @return ErrorProto object
#' 
#' @family ErrorProto functions
#' @export
ErrorProto <- function(debugInfo = NULL,location = NULL,message = NULL,reason = NULL){
structure(list(`debugInfo` = debugInfo,`location` = location,`message` = message,`reason` = reason), class = 'gar_ErrorProto')}
	
#' ExplainQueryStage Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param computeRatioAvg Relative amount of time the average shard spent on CPU-bound tasks
#' @param computeRatioMax Relative amount of time the slowest shard spent on CPU-bound tasks
#' @param id Unique ID for stage within plan
#' @param name Human-readable name for stage
#' @param readRatioAvg Relative amount of time the average shard spent reading input
#' @param readRatioMax Relative amount of time the slowest shard spent reading input
#' @param recordsRead Number of records read into the stage
#' @param recordsWritten Number of records written by the stage
#' @param steps List of operations within the stage in dependency order (approximately chronological)
#' @param waitRatioAvg Relative amount of time the average shard spent waiting to be scheduled
#' @param waitRatioMax Relative amount of time the slowest shard spent waiting to be scheduled
#' @param writeRatioAvg Relative amount of time the average shard spent on writing output
#' @param writeRatioMax Relative amount of time the slowest shard spent on writing output
#' 
#' @return ExplainQueryStage object
#' 
#' @family ExplainQueryStage functions
#' @export
ExplainQueryStage <- function(computeRatioAvg = NULL,computeRatioMax = NULL,id = NULL,name = NULL,readRatioAvg = NULL,readRatioMax = NULL,recordsRead = NULL,recordsWritten = NULL,steps = NULL,waitRatioAvg = NULL,waitRatioMax = NULL,writeRatioAvg = NULL,writeRatioMax = NULL){
structure(list(`computeRatioAvg` = computeRatioAvg,`computeRatioMax` = computeRatioMax,`id` = id,`name` = name,`readRatioAvg` = readRatioAvg,`readRatioMax` = readRatioMax,`recordsRead` = recordsRead,`recordsWritten` = recordsWritten,`steps` = steps,`waitRatioAvg` = waitRatioAvg,`waitRatioMax` = waitRatioMax,`writeRatioAvg` = writeRatioAvg,`writeRatioMax` = writeRatioMax), class = 'gar_ExplainQueryStage')}
	
#' ExplainQueryStep Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param substeps Human-readable stage descriptions
#' 
#' @return ExplainQueryStep object
#' 
#' @family ExplainQueryStep functions
#' @export
ExplainQueryStep <- function(substeps = NULL){
structure(list(`kind` = kind,`substeps` = substeps), class = 'gar_ExplainQueryStep')}
	
#' ExternalDataConfiguration Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param autodetect [Experimental] Try to detect schema and format options automatically
#' @param bigtableOptions [Optional] Additional options if sourceFormat is set to BIGTABLE
#' @param compression [Optional] The compression type of the data source
#' @param csvOptions Additional properties to set if sourceFormat is set to CSV
#' @param googleSheetsOptions [Optional] Additional options if sourceFormat is set to GOOGLE_SHEETS
#' @param ignoreUnknownValues [Optional] Indicates if BigQuery should allow extra values that are not represented in the table schema
#' @param maxBadRecords [Optional] The maximum number of bad records that BigQuery can ignore when reading data
#' @param schema [Optional] The schema for the data
#' @param sourceFormat [Required] The data format
#' @param sourceUris [Required] The fully-qualified URIs that point to your data in Google Cloud
#' 
#' @return ExternalDataConfiguration object
#' 
#' @family ExternalDataConfiguration functions
#' @export
ExternalDataConfiguration <- function(autodetect = NULL,bigtableOptions = NULL,compression = NULL,csvOptions = NULL,googleSheetsOptions = NULL,ignoreUnknownValues = NULL,maxBadRecords = NULL,schema = NULL,sourceFormat = NULL,sourceUris = NULL){
structure(list(`autodetect` = autodetect,`bigtableOptions` = bigtableOptions,`compression` = compression,`csvOptions` = csvOptions,`googleSheetsOptions` = googleSheetsOptions,`ignoreUnknownValues` = ignoreUnknownValues,`maxBadRecords` = maxBadRecords,`schema` = schema,`sourceFormat` = sourceFormat,`sourceUris` = sourceUris), class = 'gar_ExternalDataConfiguration')}
	
#' GetQueryResultsResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param cacheHit Whether the query result was fetched from the query cache
#' @param errors [Output-only] All errors and warnings encountered during the running of the job
#' @param etag A hash of this response
#' @param jobComplete Whether the query has completed or not
#' @param jobReference Reference to the BigQuery Job that was created to run the query
#' @param numDmlAffectedRows [Output-only, Experimental] The number of rows affected by a DML statement
#' @param pageToken A token used for paging results
#' @param rows An object with as many results as can be contained within the maximum permitted reply size
#' @param schema The schema of the results
#' @param totalBytesProcessed The total number of bytes processed for this query
#' @param totalRows The total number of rows in the complete query result set, which can be more than the number of rows in this single page of results
#' 
#' @return GetQueryResultsResponse object
#' 
#' @family GetQueryResultsResponse functions
#' @export
GetQueryResultsResponse <- function(cacheHit = NULL,errors = NULL,etag = NULL,jobComplete = NULL,jobReference = NULL,numDmlAffectedRows = NULL,pageToken = NULL,rows = NULL,schema = NULL,totalBytesProcessed = NULL,totalRows = NULL){
structure(list(`cacheHit` = cacheHit,`errors` = errors,`etag` = etag,`jobComplete` = jobComplete,`jobReference` = jobReference,`kind` = "bigquery#getQueryResultsResponse",`numDmlAffectedRows` = numDmlAffectedRows,`pageToken` = pageToken,`rows` = rows,`schema` = schema,`totalBytesProcessed` = totalBytesProcessed,`totalRows` = totalRows), class = 'gar_GetQueryResultsResponse')}
	
#' GoogleSheetsOptions Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param skipLeadingRows [Optional] The number of rows at the top of a sheet that BigQuery will skip when reading the data
#' 
#' @return GoogleSheetsOptions object
#' 
#' @family GoogleSheetsOptions functions
#' @export
GoogleSheetsOptions <- function(skipLeadingRows = NULL){
structure(list(`skipLeadingRows` = skipLeadingRows), class = 'gar_GoogleSheetsOptions')}
	
#' Job Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param configuration [Required] Describes the job configuration
#' @param etag [Output-only] A hash of this resource
#' @param id [Output-only] Opaque ID field of the job
#' @param jobReference [Optional] Reference describing the unique-per-user name of the job
#' @param selfLink [Output-only] A URL that can be used to access this resource again
#' @param statistics [Output-only] Information about the job, including starting time and ending time of the job
#' @param status [Output-only] The status of this job
#' @param user_email [Output-only] Email address of the user who ran the job
#' 
#' @return Job object
#' 
#' @family Job functions
#' @export
Job <- function(configuration = NULL,etag = NULL,id = NULL,jobReference = NULL,selfLink = NULL,statistics = NULL,status = NULL,user_email = NULL){
structure(list(`configuration` = configuration,`etag` = etag,`id` = id,`jobReference` = jobReference,`kind` = "bigquery#job",`selfLink` = selfLink,`statistics` = statistics,`status` = status,`user_email` = user_email), class = 'gar_Job')}
	
#' JobCancelResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param job The final state of the job
#' 
#' @return JobCancelResponse object
#' 
#' @family JobCancelResponse functions
#' @export
JobCancelResponse <- function(job = NULL){
structure(list(`job` = job,`kind` = "bigquery#jobCancelResponse"), class = 'gar_JobCancelResponse')}
	
#' JobConfiguration Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param copy [Pick one] Copies a table
#' @param dryRun [Optional] If set, don't actually run this job
#' @param extract [Pick one] Configures an extract job
#' @param load [Pick one] Configures a load job
#' @param query [Pick one] Configures a query job
#' 
#' @return JobConfiguration object
#' 
#' @family JobConfiguration functions
#' @export
JobConfiguration <- function(copy = NULL,dryRun = NULL,extract = NULL,load = NULL,query = NULL){
structure(list(`copy` = copy,`dryRun` = dryRun,`extract` = extract,`load` = load,`query` = query), class = 'gar_JobConfiguration')}
	
#' JobConfigurationExtract Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param compression [Optional] The compression type to use for exported files
#' @param destinationFormat [Optional] The exported file format
#' @param destinationUri [Pick one] DEPRECATED: Use destinationUris instead, passing only one URI as necessary
#' @param destinationUris [Pick one] A list of fully-qualified Google Cloud Storage URIs where the extracted table should be written
#' @param fieldDelimiter [Optional] Delimiter to use between fields in the exported data
#' @param printHeader [Optional] Whether to print out a header row in the results
#' @param sourceTable [Required] A reference to the table being exported
#' 
#' @return JobConfigurationExtract object
#' 
#' @family JobConfigurationExtract functions
#' @export
JobConfigurationExtract <- function(compression = NULL,destinationFormat = NULL,destinationUri = NULL,destinationUris = NULL,fieldDelimiter = NULL,printHeader = NULL,sourceTable = NULL){
structure(list(`compression` = compression,`destinationFormat` = destinationFormat,`destinationUri` = destinationUri,`destinationUris` = destinationUris,`fieldDelimiter` = fieldDelimiter,`printHeader` = "true",`sourceTable` = sourceTable), class = 'gar_JobConfigurationExtract')}
	
#' JobConfigurationLoad Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param allowJaggedRows [Optional] Accept rows that are missing trailing optional columns
#' @param allowQuotedNewlines Indicates if BigQuery should allow quoted data sections that contain newline characters in a CSV file
#' @param autodetect [Experimental] Indicates if we should automatically infer the options and schema for CSV and JSON sources
#' @param createDisposition [Optional] Specifies whether the job is allowed to create new tables
#' @param destinationTable [Required] The destination table to load the data into
#' @param encoding [Optional] The character encoding of the data
#' @param fieldDelimiter [Optional] The separator for fields in a CSV file
#' @param ignoreUnknownValues [Optional] Indicates if BigQuery should allow extra values that are not represented in the table schema
#' @param maxBadRecords [Optional] The maximum number of bad records that BigQuery can ignore when running the job
#' @param projectionFields [Experimental] If sourceFormat is set to "DATASTORE_BACKUP", indicates which entity properties to load into BigQuery from a Cloud Datastore backup
#' @param quote [Optional] The value that is used to quote data sections in a CSV file
#' @param schema [Optional] The schema for the destination table
#' @param schemaInline [Deprecated] The inline schema
#' @param schemaInlineFormat [Deprecated] The format of the schemaInline property
#' @param schemaUpdateOptions [Experimental] Allows the schema of the desitination table to be updated as a side effect of the load job
#' @param skipLeadingRows [Optional] The number of rows at the top of a CSV file that BigQuery will skip when loading the data
#' @param sourceFormat [Optional] The format of the data files
#' @param sourceUris [Required] The fully-qualified URIs that point to your data in Google Cloud Storage
#' @param writeDisposition [Optional] Specifies the action that occurs if the destination table already exists
#' 
#' @return JobConfigurationLoad object
#' 
#' @family JobConfigurationLoad functions
#' @export
JobConfigurationLoad <- function(allowJaggedRows = NULL,allowQuotedNewlines = NULL,autodetect = NULL,createDisposition = NULL,destinationTable = NULL,encoding = NULL,fieldDelimiter = NULL,ignoreUnknownValues = NULL,maxBadRecords = NULL,projectionFields = NULL,quote = NULL,schema = NULL,schemaInline = NULL,schemaInlineFormat = NULL,schemaUpdateOptions = NULL,skipLeadingRows = NULL,sourceFormat = NULL,sourceUris = NULL,writeDisposition = NULL){
structure(list(`allowJaggedRows` = allowJaggedRows,`allowQuotedNewlines` = allowQuotedNewlines,`autodetect` = autodetect,`createDisposition` = createDisposition,`destinationTable` = destinationTable,`encoding` = encoding,`fieldDelimiter` = fieldDelimiter,`ignoreUnknownValues` = ignoreUnknownValues,`maxBadRecords` = maxBadRecords,`projectionFields` = projectionFields,`quote` = """,`schema` = schema,`schemaInline` = schemaInline,`schemaInlineFormat` = schemaInlineFormat,`schemaUpdateOptions` = schemaUpdateOptions,`skipLeadingRows` = skipLeadingRows,`sourceFormat` = sourceFormat,`sourceUris` = sourceUris,`writeDisposition` = writeDisposition), class = 'gar_JobConfigurationLoad')}
	
#' JobConfigurationQuery Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param JobConfigurationQuery.tableDefinitions The \link{JobConfigurationQuery.tableDefinitions} object or list of objects
#' @param allowLargeResults If true, allows the query to produce arbitrarily large result tables at a slight cost in performance
#' @param createDisposition [Optional] Specifies whether the job is allowed to create new tables
#' @param defaultDataset [Optional] Specifies the default dataset to use for unqualified table names in the query
#' @param destinationTable [Optional] Describes the table where the query results should be stored
#' @param flattenResults [Optional] Flattens all nested and repeated fields in the query results
#' @param maximumBillingTier [Optional] Limits the billing tier for this job
#' @param maximumBytesBilled [Optional] Limits the bytes billed for this job
#' @param parameterMode [Experimental] Standard SQL only
#' @param preserveNulls [Deprecated] This property is deprecated
#' @param priority [Optional] Specifies a priority for the query
#' @param query [Required] BigQuery SQL query to execute
#' @param queryParameters [Experimental] Query parameters for Standard SQL queries
#' @param schemaUpdateOptions [Experimental] Allows the schema of the desitination table to be updated as a side effect of the query job
#' @param tableDefinitions [Optional] If querying an external data source outside of BigQuery, describes the data format, location and other properties of the data source
#' @param useLegacySql [Experimental] Specifies whether to use BigQuery's legacy SQL dialect for this query
#' @param useQueryCache [Optional] Whether to look for the result in the query cache
#' @param userDefinedFunctionResources [Experimental] Describes user-defined function resources used in the query
#' @param writeDisposition [Optional] Specifies the action that occurs if the destination table already exists
#' 
#' @return JobConfigurationQuery object
#' 
#' @family JobConfigurationQuery functions
#' @export
JobConfigurationQuery <- function(JobConfigurationQuery.tableDefinitions = NULL,allowLargeResults = NULL,createDisposition = NULL,defaultDataset = NULL,destinationTable = NULL,flattenResults = NULL,maximumBillingTier = NULL,maximumBytesBilled = NULL,parameterMode = NULL,preserveNulls = NULL,priority = NULL,query = NULL,queryParameters = NULL,schemaUpdateOptions = NULL,tableDefinitions = NULL,useLegacySql = NULL,useQueryCache = NULL,userDefinedFunctionResources = NULL,writeDisposition = NULL){
structure(list(`JobConfigurationQuery.tableDefinitions` = JobConfigurationQuery.tableDefinitions,`allowLargeResults` = allowLargeResults,`createDisposition` = createDisposition,`defaultDataset` = defaultDataset,`destinationTable` = destinationTable,`flattenResults` = "true",`maximumBillingTier` = "1",`maximumBytesBilled` = maximumBytesBilled,`parameterMode` = parameterMode,`preserveNulls` = preserveNulls,`priority` = priority,`query` = query,`queryParameters` = queryParameters,`schemaUpdateOptions` = schemaUpdateOptions,`tableDefinitions` = tableDefinitions,`useLegacySql` = useLegacySql,`useQueryCache` = "true",`userDefinedFunctionResources` = userDefinedFunctionResources,`writeDisposition` = writeDisposition), class = 'gar_JobConfigurationQuery')}
	
#' JobConfigurationQuery.tableDefinitions Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' [Optional] If querying an external data source outside of BigQuery, describes the data format, location and other properties of the data source. By defining these properties, the data source can then be queried as if it were a standard BigQuery table.
#' 
#' 
#' 
#' @return JobConfigurationQuery.tableDefinitions object
#' 
#' @family JobConfigurationQuery functions
#' @export
JobConfigurationQuery.tableDefinitions <- function(){
list()
}
	
#' JobConfigurationTableCopy Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param createDisposition [Optional] Specifies whether the job is allowed to create new tables
#' @param destinationTable [Required] The destination table
#' @param sourceTable [Pick one] Source table to copy
#' @param sourceTables [Pick one] Source tables to copy
#' @param writeDisposition [Optional] Specifies the action that occurs if the destination table already exists
#' 
#' @return JobConfigurationTableCopy object
#' 
#' @family JobConfigurationTableCopy functions
#' @export
JobConfigurationTableCopy <- function(createDisposition = NULL,destinationTable = NULL,sourceTable = NULL,sourceTables = NULL,writeDisposition = NULL){
structure(list(`createDisposition` = createDisposition,`destinationTable` = destinationTable,`sourceTable` = sourceTable,`sourceTables` = sourceTables,`writeDisposition` = writeDisposition), class = 'gar_JobConfigurationTableCopy')}
	
#' JobList Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param JobList.jobs The \link{JobList.jobs} object or list of objects
#' @param etag A hash of this page of results
#' @param jobs List of jobs that were requested
#' @param nextPageToken A token to request the next page of results
#' 
#' @return JobList object
#' 
#' @family JobList functions
#' @export
JobList <- function(JobList.jobs = NULL,etag = NULL,jobs = NULL,nextPageToken = NULL){
structure(list(`JobList.jobs` = JobList.jobs,`etag` = etag,`jobs` = jobs,`kind` = "bigquery#jobList",`nextPageToken` = nextPageToken), class = 'gar_JobList')}
	
#' JobList.jobs Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' 
#' 
#' @return JobList.jobs object
#' 
#' @family JobList functions
#' @export
JobList.jobs <- function(){
list()
}
	
#' JobReference Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param jobId [Required] The ID of the job
#' @param projectId [Required] The ID of the project containing this job
#' 
#' @return JobReference object
#' 
#' @family JobReference functions
#' @export
JobReference <- function(jobId = NULL,projectId = NULL){
structure(list(`jobId` = jobId,`projectId` = projectId), class = 'gar_JobReference')}
	
#' JobStatistics Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param creationTime [Output-only] Creation time of this job, in milliseconds since the epoch
#' @param endTime [Output-only] End time of this job, in milliseconds since the epoch
#' @param extract [Output-only] Statistics for an extract job
#' @param load [Output-only] Statistics for a load job
#' @param query [Output-only] Statistics for a query job
#' @param startTime [Output-only] Start time of this job, in milliseconds since the epoch
#' @param totalBytesProcessed [Output-only] [Deprecated] Use the bytes processed in the query statistics instead
#' 
#' @return JobStatistics object
#' 
#' @family JobStatistics functions
#' @export
JobStatistics <- function(creationTime = NULL,endTime = NULL,extract = NULL,load = NULL,query = NULL,startTime = NULL,totalBytesProcessed = NULL){
structure(list(`creationTime` = creationTime,`endTime` = endTime,`extract` = extract,`load` = load,`query` = query,`startTime` = startTime,`totalBytesProcessed` = totalBytesProcessed), class = 'gar_JobStatistics')}
	
#' JobStatistics2 Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param billingTier [Output-only] Billing tier for the job
#' @param cacheHit [Output-only] Whether the query result was fetched from the query cache
#' @param numDmlAffectedRows [Output-only, Experimental] The number of rows affected by a DML statement
#' @param queryPlan [Output-only, Experimental] Describes execution plan for the query
#' @param referencedTables [Output-only, Experimental] Referenced tables for the job
#' @param schema [Output-only, Experimental] The schema of the results
#' @param totalBytesBilled [Output-only] Total bytes billed for the job
#' @param totalBytesProcessed [Output-only] Total bytes processed for the job
#' @param undeclaredQueryParameters [Output-only, Experimental] Standard SQL only: list of undeclared query parameters detected during a dry run validation
#' 
#' @return JobStatistics2 object
#' 
#' @family JobStatistics2 functions
#' @export
JobStatistics2 <- function(billingTier = NULL,cacheHit = NULL,numDmlAffectedRows = NULL,queryPlan = NULL,referencedTables = NULL,schema = NULL,totalBytesBilled = NULL,totalBytesProcessed = NULL,undeclaredQueryParameters = NULL){
structure(list(`billingTier` = billingTier,`cacheHit` = cacheHit,`numDmlAffectedRows` = numDmlAffectedRows,`queryPlan` = queryPlan,`referencedTables` = referencedTables,`schema` = schema,`totalBytesBilled` = totalBytesBilled,`totalBytesProcessed` = totalBytesProcessed,`undeclaredQueryParameters` = undeclaredQueryParameters), class = 'gar_JobStatistics2')}
	
#' JobStatistics3 Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param inputFileBytes [Output-only] Number of bytes of source data in a load job
#' @param inputFiles [Output-only] Number of source files in a load job
#' @param outputBytes [Output-only] Size of the loaded data in bytes
#' @param outputRows [Output-only] Number of rows imported in a load job
#' 
#' @return JobStatistics3 object
#' 
#' @family JobStatistics3 functions
#' @export
JobStatistics3 <- function(inputFileBytes = NULL,inputFiles = NULL,outputBytes = NULL,outputRows = NULL){
structure(list(`inputFileBytes` = inputFileBytes,`inputFiles` = inputFiles,`outputBytes` = outputBytes,`outputRows` = outputRows), class = 'gar_JobStatistics3')}
	
#' JobStatistics4 Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param destinationUriFileCounts [Output-only] Number of files per destination URI or URI pattern specified in the extract configuration
#' 
#' @return JobStatistics4 object
#' 
#' @family JobStatistics4 functions
#' @export
JobStatistics4 <- function(destinationUriFileCounts = NULL){
structure(list(`destinationUriFileCounts` = destinationUriFileCounts), class = 'gar_JobStatistics4')}
	
#' JobStatus Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param errorResult [Output-only] Final error result of the job
#' @param errors [Output-only] All errors encountered during the running of the job
#' @param state [Output-only] Running state of the job
#' 
#' @return JobStatus object
#' 
#' @family JobStatus functions
#' @export
JobStatus <- function(errorResult = NULL,errors = NULL,state = NULL){
structure(list(`errorResult` = errorResult,`errors` = errors,`state` = state), class = 'gar_JobStatus')}
	
#' JsonObject Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Represents a single JSON object.
#' 
#' 
#' 
#' @return JsonObject object
#' 
#' @family JsonObject functions
#' @export
JsonObject <- function(){
list()
}
	
#' ProjectList Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param ProjectList.projects The \link{ProjectList.projects} object or list of objects
#' @param etag A hash of the page of results
#' @param nextPageToken A token to request the next page of results
#' @param projects Projects to which you have at least READ access
#' @param totalItems The total number of projects in the list
#' 
#' @return ProjectList object
#' 
#' @family ProjectList functions
#' @export
ProjectList <- function(ProjectList.projects = NULL,etag = NULL,nextPageToken = NULL,projects = NULL,totalItems = NULL){
structure(list(`ProjectList.projects` = ProjectList.projects,`etag` = etag,`kind` = "bigquery#projectList",`nextPageToken` = nextPageToken,`projects` = projects,`totalItems` = totalItems), class = 'gar_ProjectList')}
	
#' ProjectList.projects Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' 
#' 
#' @return ProjectList.projects object
#' 
#' @family ProjectList functions
#' @export
ProjectList.projects <- function(){
list()
}
	
#' ProjectReference Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param projectId [Required] ID of the project
#' 
#' @return ProjectReference object
#' 
#' @family ProjectReference functions
#' @export
ProjectReference <- function(projectId = NULL){
structure(list(`projectId` = projectId), class = 'gar_ProjectReference')}
	
#' QueryParameter Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param name [Optional] If unset, this is a positional parameter
#' @param parameterType [Required] The type of this parameter
#' @param parameterValue [Required] The value of this parameter
#' 
#' @return QueryParameter object
#' 
#' @family QueryParameter functions
#' @export
QueryParameter <- function(name = NULL,parameterType = NULL,parameterValue = NULL){
structure(list(`name` = name,`parameterType` = parameterType,`parameterValue` = parameterValue), class = 'gar_QueryParameter')}
	
#' QueryParameterType Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param QueryParameterType.structTypes The \link{QueryParameterType.structTypes} object or list of objects
#' @param arrayType [Optional] The type of the array's elements, if this is an array
#' @param structTypes [Optional] The types of the fields of this struct, in order, if this is a struct
#' @param type [Required] The top level type of this field
#' 
#' @return QueryParameterType object
#' 
#' @family QueryParameterType functions
#' @export
QueryParameterType <- function(QueryParameterType.structTypes = NULL,arrayType = NULL,structTypes = NULL,type = NULL){
structure(list(`QueryParameterType.structTypes` = QueryParameterType.structTypes,`arrayType` = arrayType,`structTypes` = structTypes,`type` = type), class = 'gar_QueryParameterType')}
	
#' QueryParameterType.structTypes Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' 
#' 
#' @return QueryParameterType.structTypes object
#' 
#' @family QueryParameterType functions
#' @export
QueryParameterType.structTypes <- function(){
list()
}
	
#' QueryParameterValue Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param arrayValues [Optional] The array values, if this is an array type
#' @param structValues [Optional] The struct field values, in order of the struct type's declaration
#' @param value [Optional] The value of this value, if a simple scalar type
#' 
#' @return QueryParameterValue object
#' 
#' @family QueryParameterValue functions
#' @export
QueryParameterValue <- function(arrayValues = NULL,structValues = NULL,value = NULL){
structure(list(`arrayValues` = arrayValues,`structValues` = structValues,`value` = value), class = 'gar_QueryParameterValue')}
	
#' QueryRequest Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param defaultDataset [Optional] Specifies the default datasetId and projectId to assume for any unqualified table names in the query
#' @param dryRun [Optional] If set to true, BigQuery doesn't run the job
#' @param maxResults [Optional] The maximum number of rows of data to return per page of results
#' @param parameterMode [Experimental] Standard SQL only
#' @param preserveNulls [Deprecated] This property is deprecated
#' @param query [Required] A query string, following the BigQuery query syntax, of the query to execute
#' @param queryParameters [Experimental] Query parameters for Standard SQL queries
#' @param timeoutMs [Optional] How long to wait for the query to complete, in milliseconds, before the request times out and returns
#' @param useLegacySql [Experimental] Specifies whether to use BigQuery's legacy SQL dialect for this query
#' @param useQueryCache [Optional] Whether to look for the result in the query cache
#' 
#' @return QueryRequest object
#' 
#' @family QueryRequest functions
#' @export
QueryRequest <- function(defaultDataset = NULL,dryRun = NULL,maxResults = NULL,parameterMode = NULL,preserveNulls = NULL,query = NULL,queryParameters = NULL,timeoutMs = NULL,useLegacySql = NULL,useQueryCache = NULL){
structure(list(`defaultDataset` = defaultDataset,`dryRun` = dryRun,`kind` = "bigquery#queryRequest",`maxResults` = maxResults,`parameterMode` = parameterMode,`preserveNulls` = preserveNulls,`query` = query,`queryParameters` = queryParameters,`timeoutMs` = timeoutMs,`useLegacySql` = "true",`useQueryCache` = "true"), class = 'gar_QueryRequest')}
	
#' QueryResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param cacheHit Whether the query result was fetched from the query cache
#' @param errors [Output-only] All errors and warnings encountered during the running of the job
#' @param jobComplete Whether the query has completed or not
#' @param jobReference Reference to the Job that was created to run the query
#' @param numDmlAffectedRows [Output-only, Experimental] The number of rows affected by a DML statement
#' @param pageToken A token used for paging results
#' @param rows An object with as many results as can be contained within the maximum permitted reply size
#' @param schema The schema of the results
#' @param totalBytesProcessed The total number of bytes processed for this query
#' @param totalRows The total number of rows in the complete query result set, which can be more than the number of rows in this single page of results
#' 
#' @return QueryResponse object
#' 
#' @family QueryResponse functions
#' @export
QueryResponse <- function(cacheHit = NULL,errors = NULL,jobComplete = NULL,jobReference = NULL,numDmlAffectedRows = NULL,pageToken = NULL,rows = NULL,schema = NULL,totalBytesProcessed = NULL,totalRows = NULL){
structure(list(`cacheHit` = cacheHit,`errors` = errors,`jobComplete` = jobComplete,`jobReference` = jobReference,`kind` = "bigquery#queryResponse",`numDmlAffectedRows` = numDmlAffectedRows,`pageToken` = pageToken,`rows` = rows,`schema` = schema,`totalBytesProcessed` = totalBytesProcessed,`totalRows` = totalRows), class = 'gar_QueryResponse')}
	
#' Streamingbuffer Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param estimatedBytes [Output-only] A lower-bound estimate of the number of bytes currently in the streaming buffer
#' @param estimatedRows [Output-only] A lower-bound estimate of the number of rows currently in the streaming buffer
#' @param oldestEntryTime [Output-only] Contains the timestamp of the oldest entry in the streaming buffer, in milliseconds since the epoch, if the streaming buffer is available
#' 
#' @return Streamingbuffer object
#' 
#' @family Streamingbuffer functions
#' @export
Streamingbuffer <- function(estimatedBytes = NULL,estimatedRows = NULL,oldestEntryTime = NULL){
structure(list(`estimatedBytes` = estimatedBytes,`estimatedRows` = estimatedRows,`oldestEntryTime` = oldestEntryTime), class = 'gar_Streamingbuffer')}
	
#' Table Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param creationTime [Output-only] The time when this table was created, in milliseconds since the epoch
#' @param description [Optional] A user-friendly description of this table
#' @param etag [Output-only] A hash of this resource
#' @param expirationTime [Optional] The time when this table expires, in milliseconds since the epoch
#' @param externalDataConfiguration [Optional] Describes the data format, location, and other properties of a table stored outside of BigQuery
#' @param friendlyName [Optional] A descriptive name for this table
#' @param id [Output-only] An opaque ID uniquely identifying the table
#' @param lastModifiedTime [Output-only] The time when this table was last modified, in milliseconds since the epoch
#' @param location [Output-only] The geographic location where the table resides
#' @param numBytes [Output-only] The size of this table in bytes, excluding any data in the streaming buffer
#' @param numLongTermBytes [Output-only] The number of bytes in the table that are considered "long-term storage"
#' @param numRows [Output-only] The number of rows of data in this table, excluding any data in the streaming buffer
#' @param schema [Optional] Describes the schema of this table
#' @param selfLink [Output-only] A URL that can be used to access this resource again
#' @param streamingBuffer [Output-only] Contains information regarding this table's streaming buffer, if one is present
#' @param tableReference [Required] Reference describing the ID of this table
#' @param timePartitioning [Experimental] If specified, configures time-based partitioning for this table
#' @param type [Output-only] Describes the table type
#' @param view [Optional] The view definition
#' 
#' @return Table object
#' 
#' @family Table functions
#' @export
Table <- function(creationTime = NULL,description = NULL,etag = NULL,expirationTime = NULL,externalDataConfiguration = NULL,friendlyName = NULL,id = NULL,lastModifiedTime = NULL,location = NULL,numBytes = NULL,numLongTermBytes = NULL,numRows = NULL,schema = NULL,selfLink = NULL,streamingBuffer = NULL,tableReference = NULL,timePartitioning = NULL,type = NULL,view = NULL){
structure(list(`creationTime` = creationTime,`description` = description,`etag` = etag,`expirationTime` = expirationTime,`externalDataConfiguration` = externalDataConfiguration,`friendlyName` = friendlyName,`id` = id,`kind` = "bigquery#table",`lastModifiedTime` = lastModifiedTime,`location` = location,`numBytes` = numBytes,`numLongTermBytes` = numLongTermBytes,`numRows` = numRows,`schema` = schema,`selfLink` = selfLink,`streamingBuffer` = streamingBuffer,`tableReference` = tableReference,`timePartitioning` = timePartitioning,`type` = type,`view` = view), class = 'gar_Table')}
	
#' TableCell Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param v No description
#' 
#' @return TableCell object
#' 
#' @family TableCell functions
#' @export
TableCell <- function(v = NULL){
structure(list(`v` = v), class = 'gar_TableCell')}
	
#' TableDataInsertAllRequest Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param TableDataInsertAllRequest.rows The \link{TableDataInsertAllRequest.rows} object or list of objects
#' @param ignoreUnknownValues [Optional] Accept rows that contain values that do not match the schema
#' @param rows The rows to insert
#' @param skipInvalidRows [Optional] Insert all valid rows of a request, even if invalid rows exist
#' @param templateSuffix [Experimental] If specified, treats the destination table as a base template, and inserts the rows into an instance table named "{destination}{templateSuffix}"
#' 
#' @return TableDataInsertAllRequest object
#' 
#' @family TableDataInsertAllRequest functions
#' @export
TableDataInsertAllRequest <- function(TableDataInsertAllRequest.rows = NULL,ignoreUnknownValues = NULL,rows = NULL,skipInvalidRows = NULL,templateSuffix = NULL){
structure(list(`TableDataInsertAllRequest.rows` = TableDataInsertAllRequest.rows,`ignoreUnknownValues` = ignoreUnknownValues,`kind` = "bigquery#tableDataInsertAllRequest",`rows` = rows,`skipInvalidRows` = skipInvalidRows,`templateSuffix` = templateSuffix), class = 'gar_TableDataInsertAllRequest')}
	
#' TableDataInsertAllRequest.rows Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' 
#' 
#' @return TableDataInsertAllRequest.rows object
#' 
#' @family TableDataInsertAllRequest functions
#' @export
TableDataInsertAllRequest.rows <- function(){
list()
}
	
#' TableDataInsertAllResponse Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param TableDataInsertAllResponse.insertErrors The \link{TableDataInsertAllResponse.insertErrors} object or list of objects
#' @param insertErrors An array of errors for rows that were not inserted
#' 
#' @return TableDataInsertAllResponse object
#' 
#' @family TableDataInsertAllResponse functions
#' @export
TableDataInsertAllResponse <- function(TableDataInsertAllResponse.insertErrors = NULL,insertErrors = NULL){
structure(list(`TableDataInsertAllResponse.insertErrors` = TableDataInsertAllResponse.insertErrors,`insertErrors` = insertErrors,`kind` = "bigquery#tableDataInsertAllResponse"), class = 'gar_TableDataInsertAllResponse')}
	
#' TableDataInsertAllResponse.insertErrors Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' 
#' 
#' @return TableDataInsertAllResponse.insertErrors object
#' 
#' @family TableDataInsertAllResponse functions
#' @export
TableDataInsertAllResponse.insertErrors <- function(){
list()
}
	
#' TableDataList Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param etag A hash of this page of results
#' @param pageToken A token used for paging results
#' @param rows Rows of results
#' @param totalRows The total number of rows in the complete table
#' 
#' @return TableDataList object
#' 
#' @family TableDataList functions
#' @export
TableDataList <- function(etag = NULL,pageToken = NULL,rows = NULL,totalRows = NULL){
structure(list(`etag` = etag,`kind` = "bigquery#tableDataList",`pageToken` = pageToken,`rows` = rows,`totalRows` = totalRows), class = 'gar_TableDataList')}
	
#' TableFieldSchema Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param description [Optional] The field description
#' @param fields [Optional] Describes the nested schema fields if the type property is set to RECORD
#' @param mode [Optional] The field mode
#' @param name [Required] The field name
#' @param type [Required] The field data type
#' 
#' @return TableFieldSchema object
#' 
#' @family TableFieldSchema functions
#' @export
TableFieldSchema <- function(description = NULL,fields = NULL,mode = NULL,name = NULL,type = NULL){
structure(list(`description` = description,`fields` = fields,`mode` = mode,`name` = name,`type` = type), class = 'gar_TableFieldSchema')}
	
#' TableList Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param TableList.tables The \link{TableList.tables} object or list of objects
#' @param etag A hash of this page of results
#' @param nextPageToken A token to request the next page of results
#' @param tables Tables in the requested dataset
#' @param totalItems The total number of tables in the dataset
#' 
#' @return TableList object
#' 
#' @family TableList functions
#' @export
TableList <- function(TableList.tables = NULL,etag = NULL,nextPageToken = NULL,tables = NULL,totalItems = NULL){
structure(list(`TableList.tables` = TableList.tables,`etag` = etag,`kind` = "bigquery#tableList",`nextPageToken` = nextPageToken,`tables` = tables,`totalItems` = totalItems), class = 'gar_TableList')}
	
#' TableList.tables Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' 
#' 
#' @return TableList.tables object
#' 
#' @family TableList functions
#' @export
TableList.tables <- function(){
list()
}
	
#' TableReference Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param datasetId [Required] The ID of the dataset containing this table
#' @param projectId [Required] The ID of the project containing this table
#' @param tableId [Required] The ID of the table
#' 
#' @return TableReference object
#' 
#' @family TableReference functions
#' @export
TableReference <- function(datasetId = NULL,projectId = NULL,tableId = NULL){
structure(list(`datasetId` = datasetId,`projectId` = projectId,`tableId` = tableId), class = 'gar_TableReference')}
	
#' TableRow Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param f Represents a single row in the result set, consisting of one or more fields
#' 
#' @return TableRow object
#' 
#' @family TableRow functions
#' @export
TableRow <- function(f = NULL){
structure(list(`f` = f), class = 'gar_TableRow')}
	
#' TableSchema Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param fields Describes the fields in a table
#' 
#' @return TableSchema object
#' 
#' @family TableSchema functions
#' @export
TableSchema <- function(fields = NULL){
structure(list(`fields` = fields), class = 'gar_TableSchema')}
	
#' TimePartitioning Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param expirationMs [Optional] Number of milliseconds for which to keep the storage for a partition
#' @param type [Required] The only type supported is DAY, which will generate one partition per day based on data loading time
#' 
#' @return TimePartitioning object
#' 
#' @family TimePartitioning functions
#' @export
TimePartitioning <- function(expirationMs = NULL,type = NULL){
structure(list(`expirationMs` = expirationMs,`type` = type), class = 'gar_TimePartitioning')}
	
#' UserDefinedFunctionResource Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param inlineCode [Pick one] An inline resource that contains code for a user-defined function (UDF)
#' @param resourceUri [Pick one] A code resource to load from a Google Cloud Storage URI (gs://bucket/path)
#' 
#' @return UserDefinedFunctionResource object
#' 
#' @family UserDefinedFunctionResource functions
#' @export
UserDefinedFunctionResource <- function(inlineCode = NULL,resourceUri = NULL){
structure(list(`inlineCode` = inlineCode,`resourceUri` = resourceUri), class = 'gar_UserDefinedFunctionResource')}
	

#' ViewDefinition Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param query [Required] A query that BigQuery executes when the view is referenced
#' @param useLegacySql [Experimental] Specifies whether to use BigQuery's legacy SQL for this view
#' @param userDefinedFunctionResources [Experimental] Describes user-defined function resources used in the query
#' 
#' @return ViewDefinition object
#' 
#' @family ViewDefinition functions
#' @export


ViewDefinition <- function(query = NULL,useLegacySql = NULL,userDefinedFunctionResources = NULL){



structure(list(`query` = query,`useLegacySql` = useLegacySql,`userDefinedFunctionResources` = userDefinedFunctionResources), class = 'gar_ViewDefinition')}

