#' Google Analytics API Objects 
#' Views and manages your Google Analytics data.
#' 
#' Auto-generated code by googleAuthR::gar_create_api_objects
#'  at 2016-07-31 22:24:48
#' filename: ./inst/api_objects.R
#' api_json: gar_discovery_api analytics v3
#' 
#' Objects for use by the functions created by googleAuthR::gar_create_api_skeleton

#' Account Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for Analytics account entry.
#' 
#' @param childLink Child link for an account entry
#' @param created Time the account was created
#' @param id Account ID
#' @param name Resource type for Analytics account
#' @param permissions Account name
#' @param selfLink Permissions the user has for this account
#' @param starred Link for this account
#' @param updated Indicates whether this account is starred or not
#' @param childLink Time the account was last modified
#' 
#' @return Account object
#' 
#' @export
Account <- function(childLink, created, id, name, permissions, selfLink, starred, 
    updated) {
    list(childLink = childLink, created = created, id = id, kind = "analytics#account", 
        name = name, permissions = permissions, selfLink = selfLink, starred = starred, 
        updated = updated)
}

#' Account.childLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Child link for an account entry. Points to the list of web properties for this account.
#' 
#' @param href Link to the list of web properties for this account
#' @param type Type of the child link
#' 
#' @return Account.childLink object
#' 
#' @export
Account.childLink <- function(href) {
    list(href = href, type = "analytics#webproperties")
}

#' Account.permissions Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Permissions the user has for this account.
#' 
#' @param  
#' 
#' @return Account.permissions object
#' 
#' @export
Account.permissions <- function() {
    list()
}

#' AccountRef Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for a linked account.
#' 
#' @param href Link for this account
#' @param id Account ID
#' @param name Analytics account reference
#' @param href Account name
#' 
#' @return AccountRef object
#' 
#' @export
AccountRef <- function(href, id, name) {
    list(href = href, id = id, kind = "analytics#accountRef", name = name)
}

#' AccountSummaries Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' An AccountSummary collection lists a summary of accounts, properties and views (profiles) to which the user has access. Each resource in the collection corresponds to a single AccountSummary.
#' 
#' @param items A list of AccountSummaries
#' @param itemsPerPage The maximum number of resources the response can contain, regardless of the actual number of resources returned
#' @param nextLink Collection type
#' @param previousLink Link to next page for this AccountSummary collection
#' @param startIndex Link to previous page for this AccountSummary collection
#' @param totalResults The starting index of the resources, which is 1 by default or otherwise specified by the start-index query parameter
#' @param username The total number of results for the query, regardless of the number of results in the response
#' @param items Email ID of the authenticated user
#' 
#' @return AccountSummaries object
#' 
#' @export
AccountSummaries <- function(items, itemsPerPage, nextLink, previousLink, startIndex, 
    totalResults, username) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#accountSummaries", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults, username = username)
}

#' AccountSummary Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for an Analytics AccountSummary. An AccountSummary is a lightweight tree comprised of properties/profiles.
#' 
#' @param id Account ID
#' @param name Resource type for Analytics AccountSummary
#' @param starred Account name
#' @param webProperties Indicates whether this account is starred or not
#' @param id List of web properties under this account
#' 
#' @return AccountSummary object
#' 
#' @export
AccountSummary <- function(id, name, starred, webProperties) {
    list(id = id, kind = "analytics#accountSummary", name = name, starred = starred, 
        webProperties = webProperties)
}

#' AccountTicket Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for an Analytics account ticket. The account ticket consists of the ticket ID and the basic information for the account, property and profile.
#' 
#' @param account Account for this ticket
#' @param id Account ticket ID used to access the account ticket
#' @param profile Resource type for account ticket
#' @param redirectUri View (Profile) for the account
#' @param webproperty Redirect URI where the user will be sent after accepting Terms of Service
#' @param account Web property for the account
#' 
#' @return AccountTicket object
#' 
#' @export
AccountTicket <- function(account, id, profile, redirectUri, webproperty) {
    list(account = account, id = id, kind = "analytics#accountTicket", profile = profile, 
        redirectUri = redirectUri, webproperty = webproperty)
}

#' Accounts Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' An account collection provides a list of Analytics accounts to which a user has access. The account collection is the entry point to all management information. Each resource in the collection corresponds to a single Analytics account.
#' 
#' @param items A list of accounts
#' @param itemsPerPage The maximum number of entries the response can contain, regardless of the actual number of entries returned
#' @param nextLink Collection type
#' @param previousLink Next link for this account collection
#' @param startIndex Previous link for this account collection
#' @param totalResults The starting index of the entries, which is 1 by default or otherwise specified by the start-index query parameter
#' @param username The total number of results for the query, regardless of the number of results in the response
#' @param items Email ID of the authenticated user
#' 
#' @return Accounts object
#' 
#' @export
Accounts <- function(items, itemsPerPage, nextLink, previousLink, startIndex, totalResults, 
    username) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#accounts", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults, username = username)
}

#' AdWordsAccount Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for an AdWords account.
#' 
#' @param autoTaggingEnabled True if auto-tagging is enabled on the AdWords account
#' @param customerId Customer ID
#' @param autoTaggingEnabled Resource type for AdWords account
#' 
#' @return AdWordsAccount object
#' 
#' @export
AdWordsAccount <- function(autoTaggingEnabled, customerId) {
    list(autoTaggingEnabled = autoTaggingEnabled, customerId = customerId, kind = "analytics#adWordsAccount")
}

#' AnalyticsDataimportDeleteUploadDataRequest Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Request template for the delete upload data request.
#' 
#' @param customDataImportUids A list of upload UIDs
#' 
#' @return AnalyticsDataimportDeleteUploadDataRequest object
#' 
#' @export
AnalyticsDataimportDeleteUploadDataRequest <- function(customDataImportUids) {
    list(customDataImportUids = customDataImportUids)
}

#' Column Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for a metadata column.
#' 
#' @param attributes Map of attribute name and value for this column
#' @param id Column id
#' @param attributes Resource type for Analytics column
#' 
#' @return Column object
#' 
#' @export
Column <- function(attributes, id) {
    list(attributes = attributes, id = id, kind = "analytics#column")
}

#' Column.attributes Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Map of attribute name and value for this column.
#' 
#' @param  
#' 
#' @return Column.attributes object
#' 
#' @export
Column.attributes <- function() {
    list()
}

#' Columns Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Lists columns (dimensions and metrics) for a particular report type.
#' 
#' @param attributeNames List of attributes names returned by columns
#' @param etag Etag of collection
#' @param items List of columns for a report type
#' @param totalResults Collection type
#' @param attributeNames Total number of columns returned in the response
#' 
#' @return Columns object
#' 
#' @export
Columns <- function(attributeNames, etag, items, totalResults) {
    list(attributeNames = attributeNames, etag = etag, items = items, kind = "analytics#columns", 
        totalResults = totalResults)
}

#' CustomDataSource Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for an Analytics custom data source.
#' 
#' @param accountId Account ID to which this custom data source belongs
#' @param childLink 
#' @param created Time this custom data source was created
#' @param description Description of custom data source
#' @param id Custom data source ID
#' @param importBehavior 
#' @param name Resource type for Analytics custom data source
#' @param parentLink Name of this custom data source
#' @param profilesLinked Parent link for this custom data source
#' @param selfLink IDs of views (profiles) linked to the custom data source
#' @param type Link for this Analytics custom data source
#' @param updated Type of the custom data source
#' @param uploadType Time this custom data source was last modified
#' @param webPropertyId 
#' @param accountId Web property ID of the form UA-XXXXX-YY to which this custom data source belongs
#' 
#' @return CustomDataSource object
#' 
#' @export
CustomDataSource <- function(accountId, childLink, created, description, id, importBehavior, 
    name, parentLink, profilesLinked, selfLink, updated, uploadType, webPropertyId) {
    list(accountId = accountId, childLink = childLink, created = created, description = description, 
        id = id, importBehavior = importBehavior, kind = "analytics#customDataSource", 
        name = name, parentLink = parentLink, profilesLinked = profilesLinked, selfLink = selfLink, 
        type = type, updated = updated, uploadType = uploadType, webPropertyId = webPropertyId)
}

#' CustomDataSource.childLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' No description
#' 
#' @param href Link to the list of daily uploads for this custom data source
#' @param type Value is 'analytics#dailyUploads'
#' 
#' @return CustomDataSource.childLink object
#' 
#' @export
CustomDataSource.childLink <- function(href) {
    list(href = href, type = type)
}

#' CustomDataSource.parentLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Parent link for this custom data source. Points to the web property to which this custom data source belongs.
#' 
#' @param href Link to the web property to which this custom data source belongs
#' @param type Value is 'analytics#webproperty'
#' 
#' @return CustomDataSource.parentLink object
#' 
#' @export
CustomDataSource.parentLink <- function(href) {
    list(href = href, type = "analytics#webproperty")
}

#' CustomDataSources Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Lists Analytics custom data sources to which the user has access. Each resource in the collection corresponds to a single Analytics custom data source.
#' 
#' @param items Collection of custom data sources
#' @param itemsPerPage The maximum number of resources the response can contain, regardless of the actual number of resources returned
#' @param nextLink Collection type
#' @param previousLink Link to next page for this custom data source collection
#' @param startIndex Link to previous page for this custom data source collection
#' @param totalResults The starting index of the resources, which is 1 by default or otherwise specified by the start-index query parameter
#' @param username The total number of results for the query, regardless of the number of results in the response
#' @param items Email ID of the authenticated user
#' 
#' @return CustomDataSources object
#' 
#' @export
CustomDataSources <- function(items, itemsPerPage, nextLink, previousLink, startIndex, 
    totalResults, username) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#customDataSources", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults, username = username)
}

#' CustomDimension Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for Analytics Custom Dimension.
#' 
#' @param accountId Account ID
#' @param active Boolean indicating whether the custom dimension is active
#' @param id Custom dimension ID
#' @param name Name of the custom dimension
#' @param parentLink Parent link for the custom dimension
#' @param scope Scope of the custom dimension: HIT, SESSION, USER or PRODUCT
#' @param webPropertyId Property ID
#' 
#' @return CustomDimension object
#' 
#' @export
CustomDimension <- function(accountId, active, id, name, parentLink, scope, webPropertyId) {
    list(accountId = accountId, active = active, id = id, name = name, parentLink = parentLink, 
        scope = scope, webPropertyId = webPropertyId)
}

#' CustomDimension.parentLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Parent link for the custom dimension. Points to the property to which the custom dimension belongs.
#' 
#' @param href Link to the property to which the custom dimension belongs
#' @param type Type of the parent link
#' 
#' @return CustomDimension.parentLink object
#' 
#' @export
CustomDimension.parentLink <- function(href) {
    list(href = href, type = "analytics#webproperty")
}

#' CustomDimensions Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' A custom dimension collection lists Analytics custom dimensions to which the user has access. Each resource in the collection corresponds to a single Analytics custom dimension.
#' 
#' @param items Collection of custom dimensions
#' @param itemsPerPage The maximum number of resources the response can contain, regardless of the actual number of resources returned
#' @param nextLink Collection type
#' @param previousLink Link to next page for this custom dimension collection
#' @param startIndex Link to previous page for this custom dimension collection
#' @param totalResults The starting index of the resources, which is 1 by default or otherwise specified by the start-index query parameter
#' @param username The total number of results for the query, regardless of the number of results in the response
#' @param items Email ID of the authenticated user
#' 
#' @return CustomDimensions object
#' 
#' @export
CustomDimensions <- function(items, itemsPerPage, nextLink, previousLink, startIndex, 
    totalResults, username) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#customDimensions", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults, username = username)
}

#' CustomMetric Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for Analytics Custom Metric.
#' 
#' @param accountId Account ID
#' @param active Boolean indicating whether the custom metric is active
#' @param id Custom metric ID
#' @param max_value Max value of custom metric
#' @param min_value Min value of custom metric
#' @param name Name of the custom metric
#' @param parentLink Parent link for the custom metric
#' @param scope Scope of the custom metric: HIT or PRODUCT
#' @param type Data type of custom metric
#' @param webPropertyId Property ID
#' 
#' @return CustomMetric object
#' 
#' @export
CustomMetric <- function(accountId, active, id, max_value, min_value, name, parentLink, 
    scope, webPropertyId) {
    list(accountId = accountId, active = active, id = id, max_value = max_value, 
        min_value = min_value, name = name, parentLink = parentLink, scope = scope, 
        type = type, webPropertyId = webPropertyId)
}

#' CustomMetric.parentLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Parent link for the custom metric. Points to the property to which the custom metric belongs.
#' 
#' @param href Link to the property to which the custom metric belongs
#' @param type Type of the parent link
#' 
#' @return CustomMetric.parentLink object
#' 
#' @export
CustomMetric.parentLink <- function(href) {
    list(href = href, type = "analytics#webproperty")
}

#' CustomMetrics Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' A custom metric collection lists Analytics custom metrics to which the user has access. Each resource in the collection corresponds to a single Analytics custom metric.
#' 
#' @param items Collection of custom metrics
#' @param itemsPerPage The maximum number of resources the response can contain, regardless of the actual number of resources returned
#' @param nextLink Collection type
#' @param previousLink Link to next page for this custom metric collection
#' @param startIndex Link to previous page for this custom metric collection
#' @param totalResults The starting index of the resources, which is 1 by default or otherwise specified by the start-index query parameter
#' @param username The total number of results for the query, regardless of the number of results in the response
#' @param items Email ID of the authenticated user
#' 
#' @return CustomMetrics object
#' 
#' @export
CustomMetrics <- function(items, itemsPerPage, nextLink, previousLink, startIndex, 
    totalResults, username) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#customMetrics", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults, username = username)
}

#' EntityAdWordsLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for Analytics Entity AdWords Link.
#' 
#' @param adWordsAccounts A list of AdWords client accounts
#' @param entity Web property being linked
#' @param id Entity AdWords link ID
#' @param name Resource type for entity AdWords link
#' @param profileIds Name of the link
#' @param selfLink IDs of linked Views (Profiles) represented as strings
#' @param adWordsAccounts URL link for this Google Analytics - Google AdWords link
#' 
#' @return EntityAdWordsLink object
#' 
#' @export
EntityAdWordsLink <- function(adWordsAccounts, entity, id, name, profileIds, selfLink) {
    list(adWordsAccounts = adWordsAccounts, entity = entity, id = id, kind = "analytics#entityAdWordsLink", 
        name = name, profileIds = profileIds, selfLink = selfLink)
}

#' EntityAdWordsLink.entity Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Web property being linked.
#' 
#' @param webPropertyRef 
#' 
#' @return EntityAdWordsLink.entity object
#' 
#' @export
EntityAdWordsLink.entity <- function(webPropertyRef) {
    list(webPropertyRef = webPropertyRef)
}

#' EntityAdWordsLinks Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' An entity AdWords link collection provides a list of GA-AdWords links Each resource in this collection corresponds to a single link.
#' 
#' @param items A list of entity AdWords links
#' @param itemsPerPage The maximum number of entries the response can contain, regardless of the actual number of entries returned
#' @param nextLink Collection type
#' @param previousLink Next link for this AdWords link collection
#' @param startIndex Previous link for this AdWords link collection
#' @param totalResults The starting index of the entries, which is 1 by default or otherwise specified by the start-index query parameter
#' @param items The total number of results for the query, regardless of the number of results in the response
#' 
#' @return EntityAdWordsLinks object
#' 
#' @export
EntityAdWordsLinks <- function(items, itemsPerPage, nextLink, previousLink, startIndex, 
    totalResults) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#entityAdWordsLinks", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults)
}

#' EntityUserLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for an Analytics Entity-User Link. Returns permissions that a user has for an entity.
#' 
#' @param entity Entity for this link
#' @param id Entity user link ID
#' @param permissions Resource type for entity user link
#' @param selfLink Permissions the user has for this entity
#' @param userRef Self link for this resource
#' @param entity User reference
#' 
#' @return EntityUserLink object
#' 
#' @export
EntityUserLink <- function(entity, id, permissions, selfLink, userRef) {
    list(entity = entity, id = id, kind = "analytics#entityUserLink", permissions = permissions, 
        selfLink = selfLink, userRef = userRef)
}

#' EntityUserLink.entity Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Entity for this link. It can be an account, a web property, or a view (profile).
#' 
#' @param accountRef Account for this link
#' @param profileRef View (Profile) for this link
#' @param webPropertyRef Web property for this link
#' 
#' @return EntityUserLink.entity object
#' 
#' @export
EntityUserLink.entity <- function(accountRef, profileRef, webPropertyRef) {
    list(accountRef = accountRef, profileRef = profileRef, webPropertyRef = webPropertyRef)
}

#' EntityUserLink.permissions Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Permissions the user has for this entity.
#' 
#' @param local Permissions that a user has been assigned at this very level
#' 
#' @return EntityUserLink.permissions object
#' 
#' @export
EntityUserLink.permissions <- function(local) {
    list(local = local)
}

#' EntityUserLinks Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' An entity user link collection provides a list of Analytics ACL links Each resource in this collection corresponds to a single link.
#' 
#' @param items A list of entity user links
#' @param itemsPerPage The maximum number of entries the response can contain, regardless of the actual number of entries returned
#' @param nextLink Collection type
#' @param previousLink Next link for this account collection
#' @param startIndex Previous link for this account collection
#' @param totalResults The starting index of the entries, which is 1 by default or otherwise specified by the start-index query parameter
#' @param items The total number of results for the query, regardless of the number of results in the response
#' 
#' @return EntityUserLinks object
#' 
#' @export
EntityUserLinks <- function(items, itemsPerPage, nextLink, previousLink, startIndex, 
    totalResults) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#entityUserLinks", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults)
}

#' Experiment Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for Analytics experiment resource.
#' 
#' @param accountId Account ID to which this experiment belongs
#' @param created Time the experiment was created
#' @param description Notes about this experiment
#' @param editableInGaUi If true, the end user will be able to edit the experiment via the Google Analytics user interface
#' @param endTime The ending time of the experiment (the time the status changed from RUNNING to ENDED)
#' @param equalWeighting Boolean specifying whether to distribute traffic evenly across all variations
#' @param id Experiment ID
#' @param internalWebPropertyId Internal ID for the web property to which this experiment belongs
#' @param minimumExperimentLengthInDays Resource type for an Analytics experiment
#' @param name An integer number in [3, 90]
#' @param objectiveMetric Experiment name
#' @param optimizationType The metric that the experiment is optimizing
#' @param parentLink Whether the objectiveMetric should be minimized or maximized
#' @param profileId Parent link for an experiment
#' @param reasonExperimentEnded View (Profile) ID to which this experiment belongs
#' @param rewriteVariationUrlsAsOriginal Why the experiment ended
#' @param selfLink Boolean specifying whether variations URLS are rewritten to match those of the original
#' @param servingFramework Link for this experiment
#' @param snippet The framework used to serve the experiment variations and evaluate the results
#' @param startTime The snippet of code to include on the control page(s)
#' @param status The starting time of the experiment (the time the status changed from READY_TO_RUN to RUNNING)
#' @param trafficCoverage Experiment status
#' @param updated A floating-point number in (0, 1]
#' @param variations Time the experiment was last modified
#' @param webPropertyId Array of variations
#' @param winnerConfidenceLevel Web property ID to which this experiment belongs
#' @param winnerFound A floating-point number in (0, 1)
#' @param accountId Boolean specifying whether a winner has been found for this experiment
#' 
#' @return Experiment object
#' 
#' @export
Experiment <- function(accountId, created, description, editableInGaUi, endTime, 
    equalWeighting, id, internalWebPropertyId, minimumExperimentLengthInDays, name, 
    objectiveMetric, optimizationType, parentLink, profileId, reasonExperimentEnded, 
    rewriteVariationUrlsAsOriginal, selfLink, servingFramework, snippet, startTime, 
    status, trafficCoverage, updated, variations, webPropertyId, winnerConfidenceLevel, 
    winnerFound) {
    list(accountId = accountId, created = created, description = description, editableInGaUi = editableInGaUi, 
        endTime = endTime, equalWeighting = equalWeighting, id = id, internalWebPropertyId = internalWebPropertyId, 
        kind = "analytics#experiment", minimumExperimentLengthInDays = minimumExperimentLengthInDays, 
        name = name, objectiveMetric = objectiveMetric, optimizationType = optimizationType, 
        parentLink = parentLink, profileId = profileId, reasonExperimentEnded = reasonExperimentEnded, 
        rewriteVariationUrlsAsOriginal = rewriteVariationUrlsAsOriginal, selfLink = selfLink, 
        servingFramework = servingFramework, snippet = snippet, startTime = startTime, 
        status = status, trafficCoverage = trafficCoverage, updated = updated, variations = variations, 
        webPropertyId = webPropertyId, winnerConfidenceLevel = winnerConfidenceLevel, 
        winnerFound = winnerFound)
}

#' Experiment.parentLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Parent link for an experiment. Points to the view (profile) to which this experiment belongs.
#' 
#' @param href Link to the view (profile) to which this experiment belongs
#' @param type Value is 'analytics#profile'
#' 
#' @return Experiment.parentLink object
#' 
#' @export
Experiment.parentLink <- function(href) {
    list(href = href, type = "analytics#profile")
}

#' Experiment.variations Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' No description
#' 
#' @param  
#' 
#' @return Experiment.variations object
#' 
#' @export
Experiment.variations <- function() {
    list()
}

#' Experiments Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' An experiment collection lists Analytics experiments to which the user has access. Each view (profile) can have a set of experiments. Each resource in the Experiment collection corresponds to a single Analytics experiment.
#' 
#' @param items A list of experiments
#' @param itemsPerPage The maximum number of resources the response can contain, regardless of the actual number of resources returned
#' @param nextLink Collection type
#' @param previousLink Link to next page for this experiment collection
#' @param startIndex Link to previous page for this experiment collection
#' @param totalResults The starting index of the resources, which is 1 by default or otherwise specified by the start-index query parameter
#' @param username The total number of results for the query, regardless of the number of resources in the result
#' @param items Email ID of the authenticated user
#' 
#' @return Experiments object
#' 
#' @export
Experiments <- function(items, itemsPerPage, nextLink, previousLink, startIndex, 
    totalResults, username) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#experiments", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults, username = username)
}

#' Filter Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for an Analytics account filter.
#' 
#' @param accountId Account ID to which this filter belongs
#' @param advancedDetails Details for the filter of the type ADVANCED
#' @param excludeDetails Details for the filter of the type EXCLUDE
#' @param id Filter ID
#' @param includeDetails Details for the filter of the type INCLUDE
#' @param lowercaseDetails Details for the filter of the type LOWER
#' @param name Name of this filter
#' @param parentLink Parent link for this filter
#' @param searchAndReplaceDetails Details for the filter of the type SEARCH_AND_REPLACE
#' @param type Type of this filter
#' @param uppercaseDetails Details for the filter of the type UPPER
#' 
#' @return Filter object
#' 
#' @export
Filter <- function(accountId, advancedDetails, excludeDetails, id, includeDetails, 
    lowercaseDetails, name, parentLink, searchAndReplaceDetails, uppercaseDetails) {
    list(accountId = accountId, advancedDetails = advancedDetails, excludeDetails = excludeDetails, 
        id = id, includeDetails = includeDetails, lowercaseDetails = lowercaseDetails, 
        name = name, parentLink = parentLink, searchAndReplaceDetails = searchAndReplaceDetails, 
        type = type, uppercaseDetails = uppercaseDetails)
}

#' Filter.advancedDetails Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Details for the filter of the type ADVANCED.
#' 
#' @param caseSensitive Indicates if the filter expressions are case sensitive
#' @param extractA Expression to extract from field A
#' @param extractB Expression to extract from field B
#' @param fieldA Field A
#' @param fieldAIndex The Index of the custom dimension
#' @param fieldARequired Indicates if field A is required to match
#' @param fieldB Field B
#' @param fieldBIndex The Index of the custom dimension
#' @param fieldBRequired Indicates if field B is required to match
#' @param outputConstructor Expression used to construct the output value
#' @param outputToField Output field
#' @param outputToFieldIndex The Index of the custom dimension
#' @param overrideOutputField Indicates if the existing value of the output field, if any, should be overridden by the output expression
#' 
#' @return Filter.advancedDetails object
#' 
#' @export
Filter.advancedDetails <- function(caseSensitive, extractA, extractB, fieldA, fieldAIndex, 
    fieldARequired, fieldB, fieldBIndex, fieldBRequired, outputConstructor, outputToField, 
    outputToFieldIndex, overrideOutputField) {
    list(caseSensitive = caseSensitive, extractA = extractA, extractB = extractB, 
        fieldA = fieldA, fieldAIndex = fieldAIndex, fieldARequired = fieldARequired, 
        fieldB = fieldB, fieldBIndex = fieldBIndex, fieldBRequired = fieldBRequired, 
        outputConstructor = outputConstructor, outputToField = outputToField, outputToFieldIndex = outputToFieldIndex, 
        overrideOutputField = overrideOutputField)
}

#' Filter.lowercaseDetails Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Details for the filter of the type LOWER.
#' 
#' @param field Field to use in the filter
#' @param fieldIndex The Index of the custom dimension
#' 
#' @return Filter.lowercaseDetails object
#' 
#' @export
Filter.lowercaseDetails <- function(field, fieldIndex) {
    list(field = field, fieldIndex = fieldIndex)
}

#' Filter.parentLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Parent link for this filter. Points to the account to which this filter belongs.
#' 
#' @param href Link to the account to which this filter belongs
#' @param type Value is 'analytics#account'
#' 
#' @return Filter.parentLink object
#' 
#' @export
Filter.parentLink <- function(href) {
    list(href = href, type = "analytics#account")
}

#' Filter.searchAndReplaceDetails Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Details for the filter of the type SEARCH_AND_REPLACE.
#' 
#' @param caseSensitive Determines if the filter is case sensitive
#' @param field Field to use in the filter
#' @param fieldIndex The Index of the custom dimension
#' @param replaceString Term to replace the search term with
#' @param searchString Term to search
#' 
#' @return Filter.searchAndReplaceDetails object
#' 
#' @export
Filter.searchAndReplaceDetails <- function(caseSensitive, field, fieldIndex, replaceString, 
    searchString) {
    list(caseSensitive = caseSensitive, field = field, fieldIndex = fieldIndex, replaceString = replaceString, 
        searchString = searchString)
}

#' Filter.uppercaseDetails Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Details for the filter of the type UPPER.
#' 
#' @param field Field to use in the filter
#' @param fieldIndex The Index of the custom dimension
#' 
#' @return Filter.uppercaseDetails object
#' 
#' @export
Filter.uppercaseDetails <- function(field, fieldIndex) {
    list(field = field, fieldIndex = fieldIndex)
}

#' FilterExpression Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for an Analytics filter expression.
#' 
#' @param caseSensitive Determines if the filter is case sensitive
#' @param expressionValue Filter expression value
#' @param field Field to filter
#' @param fieldIndex The Index of the custom dimension
#' @param matchType Kind value for filter expression
#' @param caseSensitive Match type for this filter
#' 
#' @return FilterExpression object
#' 
#' @export
FilterExpression <- function(caseSensitive, expressionValue, field, fieldIndex, matchType) {
    list(caseSensitive = caseSensitive, expressionValue = expressionValue, field = field, 
        fieldIndex = fieldIndex, kind = "analytics#filterExpression", matchType = matchType)
}

#' FilterRef Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for a profile filter link.
#' 
#' @param href Link for this filter
#' @param id Filter ID
#' @param href Kind value for filter reference
#' 
#' @return FilterRef object
#' 
#' @export
FilterRef <- function(href, id) {
    list(href = href, id = id, kind = "analytics#filterRef")
}

#' Filters Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' A filter collection lists filters created by users in an Analytics account. Each resource in the collection corresponds to a filter.
#' 
#' @param items A list of filters
#' @param itemsPerPage The maximum number of resources the response can contain, regardless of the actual number of resources returned
#' @param nextLink Collection type
#' @param previousLink Link to next page for this filter collection
#' @param startIndex Link to previous page for this filter collection
#' @param totalResults The starting index of the resources, which is 1 by default or otherwise specified by the start-index query parameter
#' @param username The total number of results for the query, regardless of the number of results in the response
#' @param items Email ID of the authenticated user
#' 
#' @return Filters object
#' 
#' @export
Filters <- function(items, itemsPerPage, nextLink, previousLink, startIndex, totalResults, 
    username) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#filters", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults, username = username)
}

#' GaData Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Analytics data for a given view (profile).
#' 
#' @param columnHeaders Column headers that list dimension names followed by the metric names
#' @param containsSampledData Determines if Analytics data contains samples
#' @param dataTable 
#' @param id Unique ID for this data response
#' @param itemsPerPage The maximum number of rows the response can contain, regardless of the actual number of rows returned
#' @param nextLink Resource type
#' @param previousLink Link to next page for this Analytics data query
#' @param profileInfo Link to previous page for this Analytics data query
#' @param query Information for the view (profile), for which the Analytics data was requested
#' @param rows Analytics data request query parameters
#' @param sampleSize Analytics data rows, where each row contains a list of dimension values followed by the metric values
#' @param sampleSpace The number of samples used to calculate the result
#' @param selfLink Total size of the sample space from which the samples were selected
#' @param totalResults Link to this page
#' @param totalsForAllResults The total number of rows for the query, regardless of the number of rows in the response
#' @param columnHeaders Total values for the requested metrics over all the results, not just the results returned in this response
#' 
#' @return GaData object
#' 
#' @export
GaData <- function(columnHeaders, containsSampledData, dataTable, id, itemsPerPage, 
    nextLink, previousLink, profileInfo, query, rows, sampleSize, sampleSpace, selfLink, 
    totalResults, totalsForAllResults) {
    list(columnHeaders = columnHeaders, containsSampledData = containsSampledData, 
        dataTable = dataTable, id = id, itemsPerPage = itemsPerPage, kind = "analytics#gaData", 
        nextLink = nextLink, previousLink = previousLink, profileInfo = profileInfo, 
        query = query, rows = rows, sampleSize = sampleSize, sampleSpace = sampleSpace, 
        selfLink = selfLink, totalResults = totalResults, totalsForAllResults = totalsForAllResults)
}

#' GaData.columnHeaders Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' No description
#' 
#' @param  
#' 
#' @return GaData.columnHeaders object
#' 
#' @export
GaData.columnHeaders <- function() {
    list()
}

#' GaData.dataTable Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' No description
#' 
#' @param cols 
#' @param rows 
#' 
#' @return GaData.dataTable object
#' 
#' @export
GaData.dataTable <- function(cols, rows) {
    list(cols = cols, rows = rows)
}

#' GaData.dataTable.cols Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' No description
#' 
#' @param  
#' 
#' @return GaData.dataTable.cols object
#' 
#' @export
GaData.dataTable.cols <- function() {
    list()
}

#' GaData.dataTable.rows Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' No description
#' 
#' @param  
#' 
#' @return GaData.dataTable.rows object
#' 
#' @export
GaData.dataTable.rows <- function() {
    list()
}

#' GaData.dataTable.rows.c Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' No description
#' 
#' @param  
#' 
#' @return GaData.dataTable.rows.c object
#' 
#' @export
GaData.dataTable.rows.c <- function() {
    list()
}

#' GaData.profileInfo Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Information for the view (profile), for which the Analytics data was requested.
#' 
#' @param accountId Account ID to which this view (profile) belongs
#' @param internalWebPropertyId Internal ID for the web property to which this view (profile) belongs
#' @param profileId View (Profile) ID
#' @param profileName View (Profile) name
#' @param tableId Table ID for view (profile)
#' @param webPropertyId Web Property ID to which this view (profile) belongs
#' 
#' @return GaData.profileInfo object
#' 
#' @export
GaData.profileInfo <- function(accountId, internalWebPropertyId, profileId, profileName, 
    tableId, webPropertyId) {
    list(accountId = accountId, internalWebPropertyId = internalWebPropertyId, profileId = profileId, 
        profileName = profileName, tableId = tableId, webPropertyId = webPropertyId)
}

#' GaData.query Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Analytics data request query parameters.
#' 
#' @param dimensions List of analytics dimensions
#' @param end-date End date
#' @param filters Comma-separated list of dimension or metric filters
#' @param ids Unique table ID
#' @param max-results Maximum results per page
#' @param metrics List of analytics metrics
#' @param samplingLevel Desired sampling level
#' @param segment Analytics advanced segment
#' @param sort List of dimensions or metrics based on which Analytics data is sorted
#' @param start-date Start date
#' @param start-index Start index
#' 
#' @return GaData.query object
#' 
#' @export
GaData.query <- function(dimensions, end.date, filters, ids, max.results, metrics, 
    samplingLevel, segment, sort, start.date, start.index) {
    list(dimensions = dimensions, `end-date` = end - date, filters = filters, ids = ids, 
        `max-results` = max - results, metrics = metrics, samplingLevel = samplingLevel, 
        segment = segment, sort = sort, `start-date` = start - date, `start-index` = start - 
            index)
}

#' GaData.totalsForAllResults Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Total values for the requested metrics over all the results, not just the results returned in this response. The order of the metric totals is same as the metric order specified in the request.
#' 
#' @param  
#' 
#' @return GaData.totalsForAllResults object
#' 
#' @export
GaData.totalsForAllResults <- function() {
    list()
}

#' Goal Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for Analytics goal resource.
#' 
#' @param accountId Account ID to which this goal belongs
#' @param active Determines whether this goal is active
#' @param created Time this goal was created
#' @param eventDetails Details for the goal of the type EVENT
#' @param id Goal ID
#' @param internalWebPropertyId Internal ID for the web property to which this goal belongs
#' @param name Resource type for an Analytics goal
#' @param parentLink Goal name
#' @param profileId Parent link for a goal
#' @param selfLink View (Profile) ID to which this goal belongs
#' @param type Link for this goal
#' @param updated Goal type
#' @param urlDestinationDetails Time this goal was last modified
#' @param value Details for the goal of the type URL_DESTINATION
#' @param visitNumPagesDetails Goal value
#' @param visitTimeOnSiteDetails Details for the goal of the type VISIT_NUM_PAGES
#' @param webPropertyId Details for the goal of the type VISIT_TIME_ON_SITE
#' @param accountId Web property ID to which this goal belongs
#' 
#' @return Goal object
#' 
#' @export
Goal <- function(accountId, active, created, eventDetails, id, internalWebPropertyId, 
    name, parentLink, profileId, selfLink, updated, urlDestinationDetails, value, 
    visitNumPagesDetails, visitTimeOnSiteDetails, webPropertyId) {
    list(accountId = accountId, active = active, created = created, eventDetails = eventDetails, 
        id = id, internalWebPropertyId = internalWebPropertyId, kind = "analytics#goal", 
        name = name, parentLink = parentLink, profileId = profileId, selfLink = selfLink, 
        type = type, updated = updated, urlDestinationDetails = urlDestinationDetails, 
        value = value, visitNumPagesDetails = visitNumPagesDetails, visitTimeOnSiteDetails = visitTimeOnSiteDetails, 
        webPropertyId = webPropertyId)
}

#' Goal.eventDetails Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Details for the goal of the type EVENT.
#' 
#' @param eventConditions List of event conditions
#' @param useEventValue Determines if the event value should be used as the value for this goal
#' 
#' @return Goal.eventDetails object
#' 
#' @export
Goal.eventDetails <- function(eventConditions, useEventValue) {
    list(eventConditions = eventConditions, useEventValue = useEventValue)
}

#' Goal.eventDetails.eventConditions Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' No description
#' 
#' @param  
#' 
#' @return Goal.eventDetails.eventConditions object
#' 
#' @export
Goal.eventDetails.eventConditions <- function() {
    list()
}

#' Goal.parentLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Parent link for a goal. Points to the view (profile) to which this goal belongs.
#' 
#' @param href Link to the view (profile) to which this goal belongs
#' @param type Value is 'analytics#profile'
#' 
#' @return Goal.parentLink object
#' 
#' @export
Goal.parentLink <- function(href) {
    list(href = href, type = "analytics#profile")
}

#' Goal.urlDestinationDetails Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Details for the goal of the type URL_DESTINATION.
#' 
#' @param caseSensitive Determines if the goal URL must exactly match the capitalization of visited URLs
#' @param firstStepRequired Determines if the first step in this goal is required
#' @param matchType Match type for the goal URL
#' @param steps List of steps configured for this goal funnel
#' @param url URL for this goal
#' 
#' @return Goal.urlDestinationDetails object
#' 
#' @export
Goal.urlDestinationDetails <- function(caseSensitive, firstStepRequired, matchType, 
    steps, url) {
    list(caseSensitive = caseSensitive, firstStepRequired = firstStepRequired, matchType = matchType, 
        steps = steps, url = url)
}

#' Goal.urlDestinationDetails.steps Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' No description
#' 
#' @param  
#' 
#' @return Goal.urlDestinationDetails.steps object
#' 
#' @export
Goal.urlDestinationDetails.steps <- function() {
    list()
}

#' Goal.visitNumPagesDetails Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Details for the goal of the type VISIT_NUM_PAGES.
#' 
#' @param comparisonType Type of comparison
#' @param comparisonValue Value used for this comparison
#' 
#' @return Goal.visitNumPagesDetails object
#' 
#' @export
Goal.visitNumPagesDetails <- function(comparisonType, comparisonValue) {
    list(comparisonType = comparisonType, comparisonValue = comparisonValue)
}

#' Goal.visitTimeOnSiteDetails Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Details for the goal of the type VISIT_TIME_ON_SITE.
#' 
#' @param comparisonType Type of comparison
#' @param comparisonValue Value used for this comparison
#' 
#' @return Goal.visitTimeOnSiteDetails object
#' 
#' @export
Goal.visitTimeOnSiteDetails <- function(comparisonType, comparisonValue) {
    list(comparisonType = comparisonType, comparisonValue = comparisonValue)
}

#' Goals Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' A goal collection lists Analytics goals to which the user has access. Each view (profile) can have a set of goals. Each resource in the Goal collection corresponds to a single Analytics goal.
#' 
#' @param items A list of goals
#' @param itemsPerPage The maximum number of resources the response can contain, regardless of the actual number of resources returned
#' @param nextLink Collection type
#' @param previousLink Link to next page for this goal collection
#' @param startIndex Link to previous page for this goal collection
#' @param totalResults The starting index of the resources, which is 1 by default or otherwise specified by the start-index query parameter
#' @param username The total number of results for the query, regardless of the number of resources in the result
#' @param items Email ID of the authenticated user
#' 
#' @return Goals object
#' 
#' @export
Goals <- function(items, itemsPerPage, nextLink, previousLink, startIndex, totalResults, 
    username) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#goals", nextLink = nextLink, 
        previousLink = previousLink, startIndex = startIndex, totalResults = totalResults, 
        username = username)
}

#' McfData Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Multi-Channel Funnels data for a given view (profile).
#' 
#' @param columnHeaders Column headers that list dimension names followed by the metric names
#' @param containsSampledData Determines if the Analytics data contains sampled data
#' @param id Unique ID for this data response
#' @param itemsPerPage The maximum number of rows the response can contain, regardless of the actual number of rows returned
#' @param nextLink Resource type
#' @param previousLink Link to next page for this Analytics data query
#' @param profileInfo Link to previous page for this Analytics data query
#' @param query Information for the view (profile), for which the Analytics data was requested
#' @param rows Analytics data request query parameters
#' @param sampleSize Analytics data rows, where each row contains a list of dimension values followed by the metric values
#' @param sampleSpace The number of samples used to calculate the result
#' @param selfLink Total size of the sample space from which the samples were selected
#' @param totalResults Link to this page
#' @param totalsForAllResults The total number of rows for the query, regardless of the number of rows in the response
#' @param columnHeaders Total values for the requested metrics over all the results, not just the results returned in this response
#' 
#' @return McfData object
#' 
#' @export
McfData <- function(columnHeaders, containsSampledData, id, itemsPerPage, nextLink, 
    previousLink, profileInfo, query, rows, sampleSize, sampleSpace, selfLink, totalResults, 
    totalsForAllResults) {
    list(columnHeaders = columnHeaders, containsSampledData = containsSampledData, 
        id = id, itemsPerPage = itemsPerPage, kind = "analytics#mcfData", nextLink = nextLink, 
        previousLink = previousLink, profileInfo = profileInfo, query = query, rows = rows, 
        sampleSize = sampleSize, sampleSpace = sampleSpace, selfLink = selfLink, 
        totalResults = totalResults, totalsForAllResults = totalsForAllResults)
}

#' McfData.columnHeaders Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' No description
#' 
#' @param  
#' 
#' @return McfData.columnHeaders object
#' 
#' @export
McfData.columnHeaders <- function() {
    list()
}

#' McfData.profileInfo Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Information for the view (profile), for which the Analytics data was requested.
#' 
#' @param accountId Account ID to which this view (profile) belongs
#' @param internalWebPropertyId Internal ID for the web property to which this view (profile) belongs
#' @param profileId View (Profile) ID
#' @param profileName View (Profile) name
#' @param tableId Table ID for view (profile)
#' @param webPropertyId Web Property ID to which this view (profile) belongs
#' 
#' @return McfData.profileInfo object
#' 
#' @export
McfData.profileInfo <- function(accountId, internalWebPropertyId, profileId, profileName, 
    tableId, webPropertyId) {
    list(accountId = accountId, internalWebPropertyId = internalWebPropertyId, profileId = profileId, 
        profileName = profileName, tableId = tableId, webPropertyId = webPropertyId)
}

#' McfData.query Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Analytics data request query parameters.
#' 
#' @param dimensions List of analytics dimensions
#' @param end-date End date
#' @param filters Comma-separated list of dimension or metric filters
#' @param ids Unique table ID
#' @param max-results Maximum results per page
#' @param metrics List of analytics metrics
#' @param samplingLevel Desired sampling level
#' @param segment Analytics advanced segment
#' @param sort List of dimensions or metrics based on which Analytics data is sorted
#' @param start-date Start date
#' @param start-index Start index
#' 
#' @return McfData.query object
#' 
#' @export
McfData.query <- function(dimensions, end.date, filters, ids, max.results, metrics, 
    samplingLevel, segment, sort, start.date, start.index) {
    list(dimensions = dimensions, `end-date` = end - date, filters = filters, ids = ids, 
        `max-results` = max - results, metrics = metrics, samplingLevel = samplingLevel, 
        segment = segment, sort = sort, `start-date` = start - date, `start-index` = start - 
            index)
}

#' McfData.totalsForAllResults Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Total values for the requested metrics over all the results, not just the results returned in this response. The order of the metric totals is same as the metric order specified in the request.
#' 
#' @param  
#' 
#' @return McfData.totalsForAllResults object
#' 
#' @export
McfData.totalsForAllResults <- function() {
    list()
}

#' Profile Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for an Analytics view (profile).
#' 
#' @param accountId Account ID to which this view (profile) belongs
#' @param botFilteringEnabled Indicates whether bot filtering is enabled for this view (profile)
#' @param childLink Child link for this view (profile)
#' @param currency The currency type associated with this view (profile), defaults to USD
#' @param defaultPage Default page for this view (profile)
#' @param eCommerceTracking Indicates whether ecommerce tracking is enabled for this view (profile)
#' @param enhancedECommerceTracking Indicates whether enhanced ecommerce tracking is enabled for this view (profile)
#' @param excludeQueryParameters The query parameters that are excluded from this view (profile)
#' @param id View (Profile) ID
#' @param name Name of this view (profile)
#' @param parentLink Parent link for this view (profile)
#' @param permissions Permissions the user has for this view (profile)
#' @param siteSearchCategoryParameters Site search category parameters for this view (profile)
#' @param siteSearchQueryParameters The site search query parameters for this view (profile)
#' @param starred Indicates whether this view (profile) is starred or not
#' @param stripSiteSearchCategoryParameters Whether or not Analytics will strip search category parameters from the URLs in your reports
#' @param stripSiteSearchQueryParameters Whether or not Analytics will strip search query parameters from the URLs in your reports
#' @param timezone Time zone for which this view (profile) has been configured
#' @param type View (Profile) type
#' @param websiteUrl Website URL for this view (profile)
#' 
#' @return Profile object
#' 
#' @export
Profile <- function(accountId, botFilteringEnabled, childLink, currency, defaultPage, 
    eCommerceTracking, enhancedECommerceTracking, excludeQueryParameters, id, name, 
    parentLink, permissions, siteSearchCategoryParameters, siteSearchQueryParameters, 
    starred, stripSiteSearchCategoryParameters, stripSiteSearchQueryParameters, timezone, 
    websiteUrl) {
    list(accountId = accountId, botFilteringEnabled = botFilteringEnabled, childLink = childLink, 
        currency = currency, defaultPage = defaultPage, eCommerceTracking = eCommerceTracking, 
        enhancedECommerceTracking = enhancedECommerceTracking, excludeQueryParameters = excludeQueryParameters, 
        id = id, name = name, parentLink = parentLink, permissions = permissions, 
        siteSearchCategoryParameters = siteSearchCategoryParameters, siteSearchQueryParameters = siteSearchQueryParameters, 
        starred = starred, stripSiteSearchCategoryParameters = stripSiteSearchCategoryParameters, 
        stripSiteSearchQueryParameters = stripSiteSearchQueryParameters, timezone = timezone, 
        type = type, websiteUrl = websiteUrl)
}

#' Profile.childLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Child link for this view (profile). Points to the list of goals for this view (profile).
#' 
#' @param href Link to the list of goals for this view (profile)
#' @param type Value is 'analytics#goals'
#' 
#' @return Profile.childLink object
#' 
#' @export
Profile.childLink <- function(href) {
    list(href = href, type = "analytics#goals")
}

#' Profile.parentLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Parent link for this view (profile). Points to the web property to which this view (profile) belongs.
#' 
#' @param href Link to the web property to which this view (profile) belongs
#' @param type Value is 'analytics#webproperty'
#' 
#' @return Profile.parentLink object
#' 
#' @export
Profile.parentLink <- function(href) {
    list(href = href, type = "analytics#webproperty")
}

#' Profile.permissions Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Permissions the user has for this view (profile).
#' 
#' @param  
#' 
#' @return Profile.permissions object
#' 
#' @export
Profile.permissions <- function() {
    list()
}

#' ProfileFilterLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for an Analytics profile filter link.
#' 
#' @param filterRef Filter for this link
#' @param id Profile filter link ID
#' @param profileRef View (Profile) for this link
#' @param rank The rank of this profile filter link relative to the other filters linked to the same profile
#' 
#' @return ProfileFilterLink object
#' 
#' @export
ProfileFilterLink <- function(filterRef, id, profileRef, rank) {
    list(filterRef = filterRef, id = id, profileRef = profileRef, rank = rank)
}

#' ProfileFilterLinks Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' A profile filter link collection lists profile filter links between profiles and filters. Each resource in the collection corresponds to a profile filter link.
#' 
#' @param items A list of profile filter links
#' @param itemsPerPage The maximum number of resources the response can contain, regardless of the actual number of resources returned
#' @param nextLink Collection type
#' @param previousLink Link to next page for this profile filter link collection
#' @param startIndex Link to previous page for this profile filter link collection
#' @param totalResults The starting index of the resources, which is 1 by default or otherwise specified by the start-index query parameter
#' @param username The total number of results for the query, regardless of the number of results in the response
#' @param items Email ID of the authenticated user
#' 
#' @return ProfileFilterLinks object
#' 
#' @export
ProfileFilterLinks <- function(items, itemsPerPage, nextLink, previousLink, startIndex, 
    totalResults, username) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#profileFilterLinks", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults, username = username)
}

#' ProfileRef Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for a linked view (profile).
#' 
#' @param accountId Account ID to which this view (profile) belongs
#' @param href Link for this view (profile)
#' @param id View (Profile) ID
#' @param internalWebPropertyId Internal ID for the web property to which this view (profile) belongs
#' @param name Analytics view (profile) reference
#' @param webPropertyId Name of this view (profile)
#' @param accountId Web property ID of the form UA-XXXXX-YY to which this view (profile) belongs
#' 
#' @return ProfileRef object
#' 
#' @export
ProfileRef <- function(accountId, href, id, internalWebPropertyId, name, webPropertyId) {
    list(accountId = accountId, href = href, id = id, internalWebPropertyId = internalWebPropertyId, 
        kind = "analytics#profileRef", name = name, webPropertyId = webPropertyId)
}

#' ProfileSummary Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for an Analytics ProfileSummary. ProfileSummary returns basic information (i.e., summary) for a profile.
#' 
#' @param id View (profile) ID
#' @param name Resource type for Analytics ProfileSummary
#' @param starred View (profile) name
#' @param type Indicates whether this view (profile) is starred or not
#' @param id View (Profile) type
#' 
#' @return ProfileSummary object
#' 
#' @export
ProfileSummary <- function(id, name, starred) {
    list(id = id, kind = "analytics#profileSummary", name = name, starred = starred, 
        type = type)
}

#' Profiles Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' A view (profile) collection lists Analytics views (profiles) to which the user has access. Each resource in the collection corresponds to a single Analytics view (profile).
#' 
#' @param items A list of views (profiles)
#' @param itemsPerPage The maximum number of resources the response can contain, regardless of the actual number of resources returned
#' @param nextLink Collection type
#' @param previousLink Link to next page for this view (profile) collection
#' @param startIndex Link to previous page for this view (profile) collection
#' @param totalResults The starting index of the resources, which is 1 by default or otherwise specified by the start-index query parameter
#' @param username The total number of results for the query, regardless of the number of results in the response
#' @param items Email ID of the authenticated user
#' 
#' @return Profiles object
#' 
#' @export
Profiles <- function(items, itemsPerPage, nextLink, previousLink, startIndex, totalResults, 
    username) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#profiles", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults, username = username)
}

#' RealtimeData Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Real time data for a given view (profile).
#' 
#' @param columnHeaders Column headers that list dimension names followed by the metric names
#' @param id Unique ID for this data response
#' @param profileInfo Resource type
#' @param query Information for the view (profile), for which the real time data was requested
#' @param rows Real time data request query parameters
#' @param selfLink Real time data rows, where each row contains a list of dimension values followed by the metric values
#' @param totalResults Link to this page
#' @param totalsForAllResults The total number of rows for the query, regardless of the number of rows in the response
#' @param columnHeaders Total values for the requested metrics over all the results, not just the results returned in this response
#' 
#' @return RealtimeData object
#' 
#' @export
RealtimeData <- function(columnHeaders, id, profileInfo, query, rows, selfLink, totalResults, 
    totalsForAllResults) {
    list(columnHeaders = columnHeaders, id = id, kind = "analytics#realtimeData", 
        profileInfo = profileInfo, query = query, rows = rows, selfLink = selfLink, 
        totalResults = totalResults, totalsForAllResults = totalsForAllResults)
}

#' RealtimeData.columnHeaders Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' No description
#' 
#' @param  
#' 
#' @return RealtimeData.columnHeaders object
#' 
#' @export
RealtimeData.columnHeaders <- function() {
    list()
}

#' RealtimeData.profileInfo Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Information for the view (profile), for which the real time data was requested.
#' 
#' @param accountId Account ID to which this view (profile) belongs
#' @param internalWebPropertyId Internal ID for the web property to which this view (profile) belongs
#' @param profileId View (Profile) ID
#' @param profileName View (Profile) name
#' @param tableId Table ID for view (profile)
#' @param webPropertyId Web Property ID to which this view (profile) belongs
#' 
#' @return RealtimeData.profileInfo object
#' 
#' @export
RealtimeData.profileInfo <- function(accountId, internalWebPropertyId, profileId, 
    profileName, tableId, webPropertyId) {
    list(accountId = accountId, internalWebPropertyId = internalWebPropertyId, profileId = profileId, 
        profileName = profileName, tableId = tableId, webPropertyId = webPropertyId)
}

#' RealtimeData.query Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Real time data request query parameters.
#' 
#' @param dimensions List of real time dimensions
#' @param filters Comma-separated list of dimension or metric filters
#' @param ids Unique table ID
#' @param max-results Maximum results per page
#' @param metrics List of real time metrics
#' @param sort List of dimensions or metrics based on which real time data is sorted
#' 
#' @return RealtimeData.query object
#' 
#' @export
RealtimeData.query <- function(dimensions, filters, ids, max.results, metrics, sort) {
    list(dimensions = dimensions, filters = filters, ids = ids, `max-results` = max - 
        results, metrics = metrics, sort = sort)
}

#' RealtimeData.totalsForAllResults Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Total values for the requested metrics over all the results, not just the results returned in this response. The order of the metric totals is same as the metric order specified in the request.
#' 
#' @param  
#' 
#' @return RealtimeData.totalsForAllResults object
#' 
#' @export
RealtimeData.totalsForAllResults <- function() {
    list()
}

#' Segment Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for an Analytics segment.
#' 
#' @param created Time the segment was created
#' @param definition Segment definition
#' @param id Segment ID
#' @param name Resource type for Analytics segment
#' @param segmentId Segment name
#' @param selfLink Segment ID
#' @param type Link for this segment
#' @param updated Type for a segment
#' @param created Time the segment was last modified
#' 
#' @return Segment object
#' 
#' @export
Segment <- function(created, definition, id, name, segmentId, selfLink, updated) {
    list(created = created, definition = definition, id = id, kind = "analytics#segment", 
        name = name, segmentId = segmentId, selfLink = selfLink, type = type, updated = updated)
}

#' Segments Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' An segment collection lists Analytics segments that the user has access to. Each resource in the collection corresponds to a single Analytics segment.
#' 
#' @param items A list of segments
#' @param itemsPerPage The maximum number of resources the response can contain, regardless of the actual number of resources returned
#' @param nextLink Collection type for segments
#' @param previousLink Link to next page for this segment collection
#' @param startIndex Link to previous page for this segment collection
#' @param totalResults The starting index of the resources, which is 1 by default or otherwise specified by the start-index query parameter
#' @param username The total number of results for the query, regardless of the number of results in the response
#' @param items Email ID of the authenticated user
#' 
#' @return Segments object
#' 
#' @export
Segments <- function(items, itemsPerPage, nextLink, previousLink, startIndex, totalResults, 
    username) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#segments", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults, username = username)
}

#' UnsampledReport Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for Analytics unsampled report resource.
#' 
#' @param accountId Account ID to which this unsampled report belongs
#' @param dimensions The dimensions for the unsampled report
#' @param end-date The end date for the unsampled report
#' @param filters The filters for the unsampled report
#' @param id Unsampled report ID
#' @param metrics The metrics for the unsampled report
#' @param profileId View (Profile) ID to which this unsampled report belongs
#' @param segment The segment for the unsampled report
#' @param start-date The start date for the unsampled report
#' @param title Title of the unsampled report
#' @param webPropertyId Web property ID to which this unsampled report belongs
#' 
#' @return UnsampledReport object
#' 
#' @export
UnsampledReport <- function(accountId, dimensions, end.date, filters, id, metrics, 
    profileId, segment, start.date, title, webPropertyId) {
    list(accountId = accountId, dimensions = dimensions, `end-date` = end - date, 
        filters = filters, id = id, metrics = metrics, profileId = profileId, segment = segment, 
        `start-date` = start - date, title = title, webPropertyId = webPropertyId)
}

#' UnsampledReport.cloudStorageDownloadDetails Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Download details for a file stored in Google Cloud Storage.
#' 
#' @param bucketId Id of the bucket the file object is stored in
#' @param objectId Id of the file object containing the report data
#' 
#' @return UnsampledReport.cloudStorageDownloadDetails object
#' 
#' @export
UnsampledReport.cloudStorageDownloadDetails <- function(bucketId, objectId) {
    list(bucketId = bucketId, objectId = objectId)
}

#' UnsampledReport.driveDownloadDetails Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Download details for a file stored in Google Drive.
#' 
#' @param documentId Id of the document/file containing the report data
#' 
#' @return UnsampledReport.driveDownloadDetails object
#' 
#' @export
UnsampledReport.driveDownloadDetails <- function(documentId) {
    list(documentId = documentId)
}

#' UnsampledReports Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' An unsampled report collection lists Analytics unsampled reports to which the user has access. Each view (profile) can have a set of unsampled reports. Each resource in the unsampled report collection corresponds to a single Analytics unsampled report.
#' 
#' @param items A list of unsampled reports
#' @param itemsPerPage The maximum number of resources the response can contain, regardless of the actual number of resources returned
#' @param nextLink Collection type
#' @param previousLink Link to next page for this unsampled report collection
#' @param startIndex Link to previous page for this unsampled report collection
#' @param totalResults The starting index of the resources, which is 1 by default or otherwise specified by the start-index query parameter
#' @param username The total number of results for the query, regardless of the number of resources in the result
#' @param items Email ID of the authenticated user
#' 
#' @return UnsampledReports object
#' 
#' @export
UnsampledReports <- function(items, itemsPerPage, nextLink, previousLink, startIndex, 
    totalResults, username) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#unsampledReports", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults, username = username)
}

#' Upload Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Metadata returned for an upload operation.
#' 
#' @param accountId Account Id to which this upload belongs
#' @param customDataSourceId Custom data source Id to which this data import belongs
#' @param errors Data import errors collection
#' @param id A unique ID for this upload
#' @param status Resource type for Analytics upload
#' @param accountId Upload status
#' 
#' @return Upload object
#' 
#' @export
Upload <- function(accountId, customDataSourceId, errors, id, status) {
    list(accountId = accountId, customDataSourceId = customDataSourceId, errors = errors, 
        id = id, kind = "analytics#upload", status = status)
}

#' Uploads Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Upload collection lists Analytics uploads to which the user has access. Each custom data source can have a set of uploads. Each resource in the upload collection corresponds to a single Analytics data upload.
#' 
#' @param items A list of uploads
#' @param itemsPerPage The maximum number of resources the response can contain, regardless of the actual number of resources returned
#' @param nextLink Collection type
#' @param previousLink Link to next page for this upload collection
#' @param startIndex Link to previous page for this upload collection
#' @param totalResults The starting index of the resources, which is 1 by default or otherwise specified by the start-index query parameter
#' @param items The total number of results for the query, regardless of the number of resources in the result
#' 
#' @return Uploads object
#' 
#' @export
Uploads <- function(items, itemsPerPage, nextLink, previousLink, startIndex, totalResults) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#uploads", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults)
}

#' UserRef Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for a user reference.
#' 
#' @param email Email ID of this user
#' @param id User ID
#' @param email 
#' 
#' @return UserRef object
#' 
#' @export
UserRef <- function(email, id) {
    list(email = email, id = id, kind = "analytics#userRef")
}

#' WebPropertyRef Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for a web property reference.
#' 
#' @param accountId Account ID to which this web property belongs
#' @param href Link for this web property
#' @param id Web property ID of the form UA-XXXXX-YY
#' @param internalWebPropertyId Internal ID for this web property
#' @param name Analytics web property reference
#' @param accountId Name of this web property
#' 
#' @return WebPropertyRef object
#' 
#' @export
WebPropertyRef <- function(accountId, href, id, internalWebPropertyId, name) {
    list(accountId = accountId, href = href, id = id, internalWebPropertyId = internalWebPropertyId, 
        kind = "analytics#webPropertyRef", name = name)
}

#' WebPropertySummary Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for an Analytics WebPropertySummary. WebPropertySummary returns basic information (i.e., summary) for a web property.
#' 
#' @param id Web property ID of the form UA-XXXXX-YY
#' @param internalWebPropertyId Internal ID for this web property
#' @param level Resource type for Analytics WebPropertySummary
#' @param name Level for this web property
#' @param profiles Web property name
#' @param starred List of profiles under this web property
#' @param websiteUrl Indicates whether this web property is starred or not
#' @param id Website url for this web property
#' 
#' @return WebPropertySummary object
#' 
#' @export
WebPropertySummary <- function(id, internalWebPropertyId, level, name, profiles, 
    starred, websiteUrl) {
    list(id = id, internalWebPropertyId = internalWebPropertyId, kind = "analytics#webPropertySummary", 
        level = level, name = name, profiles = profiles, starred = starred, websiteUrl = websiteUrl)
}

#' Webproperties Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' A web property collection lists Analytics web properties to which the user has access. Each resource in the collection corresponds to a single Analytics web property.
#' 
#' @param items A list of web properties
#' @param itemsPerPage The maximum number of resources the response can contain, regardless of the actual number of resources returned
#' @param nextLink Collection type
#' @param previousLink Link to next page for this web property collection
#' @param startIndex Link to previous page for this web property collection
#' @param totalResults The starting index of the resources, which is 1 by default or otherwise specified by the start-index query parameter
#' @param username The total number of results for the query, regardless of the number of results in the response
#' @param items Email ID of the authenticated user
#' 
#' @return Webproperties object
#' 
#' @export
Webproperties <- function(items, itemsPerPage, nextLink, previousLink, startIndex, 
    totalResults, username) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#webproperties", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults, username = username)
}

#' Webproperty Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for an Analytics web property.
#' 
#' @param accountId Account ID to which this web property belongs
#' @param childLink Child link for this web property
#' @param defaultProfileId Default view (profile) ID
#' @param id Web property ID of the form UA-XXXXX-YY
#' @param industryVertical The industry vertical/category selected for this web property
#' @param name Name of this web property
#' @param parentLink Parent link for this web property
#' @param permissions Permissions the user has for this web property
#' @param starred Indicates whether this web property is starred or not
#' @param websiteUrl Website url for this web property
#' 
#' @return Webproperty object
#' 
#' @export
Webproperty <- function(accountId, childLink, defaultProfileId, id, industryVertical, 
    name, parentLink, permissions, starred, websiteUrl) {
    list(accountId = accountId, childLink = childLink, defaultProfileId = defaultProfileId, 
        id = id, industryVertical = industryVertical, name = name, parentLink = parentLink, 
        permissions = permissions, starred = starred, websiteUrl = websiteUrl)
}

#' Webproperty.childLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Child link for this web property. Points to the list of views (profiles) for this web property.
#' 
#' @param href Link to the list of views (profiles) for this web property
#' @param type Type of the parent link
#' 
#' @return Webproperty.childLink object
#' 
#' @export
Webproperty.childLink <- function(href) {
    list(href = href, type = "analytics#profiles")
}

#' Webproperty.parentLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Parent link for this web property. Points to the account to which this web property belongs.
#' 
#' @param href Link to the account for this web property
#' @param type Type of the parent link
#' 
#' @return Webproperty.parentLink object
#' 
#' @export
Webproperty.parentLink <- function(href) {
    list(href = href, type = "analytics#account")
}


#' Webproperty.permissions Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Permissions the user has for this web property.
#' 
#' @param  
#' 
#' @return Webproperty.permissions object
#' 
#' @export


Webproperty.permissions <- function() {
    
    
    
    list()
    
}

