#' Google Analytics API Objects 
#' Views and manages your Google Analytics data.
#' 
#' Auto-generated code by googleAuthR::gar_create_api_objects
#'  at 2016-07-28 13:00:12
#' filename: ./inst/api_objects.R
#' api_json: api_json
#' 
#' Objects for use by the functions created by googleAuthR::gar_create_api_skeleton

#' Account Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for Analytics account entry.
#' 
#' @param childLink childLink
#' @param created created
#' @param id id
#' @param name name
#' @param permissions permissions
#' @param selfLink selfLink
#' @param starred starred
#' @param updated updated
#' 
#' @return Account object
#' 
#' @export
Account <- function(childLink, created, id, name, permissions, selfLink, starred, 
    updated) {
    list(childLink = childLink, created = created, id = id, kind = "analytics#account", 
        name = name, permissions = permissions, selfLink = selfLink, starred = starred, 
        updated = updated)
}

#' Account.childLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Child link for an account entry. Points to the list of web properties for this account.
#' 
#' @param href href
#' @param type type
#' 
#' @return Account.childLink object
#' 
#' @export
Account.childLink <- function(href) {
    list(href = href, type = "analytics#webproperties")
}

#' Account.permissions Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Permissions the user has for this account.
#' 
#' @param  
#' 
#' @return Account.permissions object
#' 
#' @export
Account.permissions <- function() {
    list()
}

#' AccountRef Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for a linked account.
#' 
#' @param href href
#' @param id id
#' @param name name
#' 
#' @return AccountRef object
#' 
#' @export
AccountRef <- function(href, id, name) {
    list(href = href, id = id, kind = "analytics#accountRef", name = name)
}

#' AccountSummaries Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' An AccountSummary collection lists a summary of accounts, properties and views (profiles) to which the user has access. Each resource in the collection corresponds to a single AccountSummary.
#' 
#' @param items items
#' @param itemsPerPage itemsPerPage
#' @param nextLink nextLink
#' @param previousLink previousLink
#' @param startIndex startIndex
#' @param totalResults totalResults
#' @param username username
#' 
#' @return AccountSummaries object
#' 
#' @export
AccountSummaries <- function(items, itemsPerPage, nextLink, previousLink, startIndex, 
    totalResults, username) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#accountSummaries", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults, username = username)
}

#' AccountSummary Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for an Analytics AccountSummary. An AccountSummary is a lightweight tree comprised of properties/profiles.
#' 
#' @param id id
#' @param name name
#' @param starred starred
#' @param webProperties webProperties
#' 
#' @return AccountSummary object
#' 
#' @export
AccountSummary <- function(id, name, starred, webProperties) {
    list(id = id, kind = "analytics#accountSummary", name = name, starred = starred, 
        webProperties = webProperties)
}

#' AccountTicket Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for an Analytics account ticket. The account ticket consists of the ticket ID and the basic information for the account, property and profile.
#' 
#' @param account account
#' @param id id
#' @param profile profile
#' @param redirectUri redirectUri
#' @param webproperty webproperty
#' 
#' @return AccountTicket object
#' 
#' @export
AccountTicket <- function(account, id, profile, redirectUri, webproperty) {
    list(account = account, id = id, kind = "analytics#accountTicket", profile = profile, 
        redirectUri = redirectUri, webproperty = webproperty)
}

#' Accounts Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' An account collection provides a list of Analytics accounts to which a user has access. The account collection is the entry point to all management information. Each resource in the collection corresponds to a single Analytics account.
#' 
#' @param items items
#' @param itemsPerPage itemsPerPage
#' @param nextLink nextLink
#' @param previousLink previousLink
#' @param startIndex startIndex
#' @param totalResults totalResults
#' @param username username
#' 
#' @return Accounts object
#' 
#' @export
Accounts <- function(items, itemsPerPage, nextLink, previousLink, startIndex, totalResults, 
    username) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#accounts", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults, username = username)
}

#' AdWordsAccount Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for an AdWords account.
#' 
#' @param autoTaggingEnabled autoTaggingEnabled
#' @param customerId customerId
#' 
#' @return AdWordsAccount object
#' 
#' @export
AdWordsAccount <- function(autoTaggingEnabled, customerId) {
    list(autoTaggingEnabled = autoTaggingEnabled, customerId = customerId, kind = "analytics#adWordsAccount")
}

#' AnalyticsDataimportDeleteUploadDataRequest Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Request template for the delete upload data request.
#' 
#' @param customDataImportUids customDataImportUids
#' 
#' @return AnalyticsDataimportDeleteUploadDataRequest object
#' 
#' @export
AnalyticsDataimportDeleteUploadDataRequest <- function(customDataImportUids) {
    list(customDataImportUids = customDataImportUids)
}

#' Column Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for a metadata column.
#' 
#' @param attributes attributes
#' @param id id
#' 
#' @return Column object
#' 
#' @export
Column <- function(attributes, id) {
    list(attributes = attributes, id = id, kind = "analytics#column")
}

#' Column.attributes Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Map of attribute name and value for this column.
#' 
#' @param  
#' 
#' @return Column.attributes object
#' 
#' @export
Column.attributes <- function() {
    list()
}

#' Columns Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Lists columns (dimensions and metrics) for a particular report type.
#' 
#' @param attributeNames attributeNames
#' @param etag etag
#' @param items items
#' @param totalResults totalResults
#' 
#' @return Columns object
#' 
#' @export
Columns <- function(attributeNames, etag, items, totalResults) {
    list(attributeNames = attributeNames, etag = etag, items = items, kind = "analytics#columns", 
        totalResults = totalResults)
}

#' CustomDataSource Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for an Analytics custom data source.
#' 
#' @param accountId accountId
#' @param childLink childLink
#' @param created created
#' @param description description
#' @param id id
#' @param importBehavior importBehavior
#' @param name name
#' @param parentLink parentLink
#' @param profilesLinked profilesLinked
#' @param selfLink selfLink
#' @param type type
#' @param updated updated
#' @param uploadType uploadType
#' @param webPropertyId webPropertyId
#' 
#' @return CustomDataSource object
#' 
#' @export
CustomDataSource <- function(accountId, childLink, created, description, id, importBehavior, 
    name, parentLink, profilesLinked, selfLink, updated, uploadType, webPropertyId) {
    list(accountId = accountId, childLink = childLink, created = created, description = description, 
        id = id, importBehavior = importBehavior, kind = "analytics#customDataSource", 
        name = name, parentLink = parentLink, profilesLinked = profilesLinked, selfLink = selfLink, 
        type = type, updated = updated, uploadType = uploadType, webPropertyId = webPropertyId)
}

#' CustomDataSource.childLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' No description
#' 
#' @param href href
#' @param type type
#' 
#' @return CustomDataSource.childLink object
#' 
#' @export
CustomDataSource.childLink <- function(href) {
    list(href = href, type = type)
}

#' CustomDataSource.parentLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Parent link for this custom data source. Points to the web property to which this custom data source belongs.
#' 
#' @param href href
#' @param type type
#' 
#' @return CustomDataSource.parentLink object
#' 
#' @export
CustomDataSource.parentLink <- function(href) {
    list(href = href, type = "analytics#webproperty")
}

#' CustomDataSources Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Lists Analytics custom data sources to which the user has access. Each resource in the collection corresponds to a single Analytics custom data source.
#' 
#' @param items items
#' @param itemsPerPage itemsPerPage
#' @param nextLink nextLink
#' @param previousLink previousLink
#' @param startIndex startIndex
#' @param totalResults totalResults
#' @param username username
#' 
#' @return CustomDataSources object
#' 
#' @export
CustomDataSources <- function(items, itemsPerPage, nextLink, previousLink, startIndex, 
    totalResults, username) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#customDataSources", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults, username = username)
}

#' CustomDimension Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for Analytics Custom Dimension.
#' 
#' @param accountId accountId
#' @param active active
#' @param id id
#' @param name name
#' @param parentLink parentLink
#' @param scope scope
#' @param webPropertyId webPropertyId
#' 
#' @return CustomDimension object
#' 
#' @export
CustomDimension <- function(accountId, active, id, name, parentLink, scope, webPropertyId) {
    list(accountId = accountId, active = active, id = id, name = name, parentLink = parentLink, 
        scope = scope, webPropertyId = webPropertyId)
}

#' CustomDimension.parentLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Parent link for the custom dimension. Points to the property to which the custom dimension belongs.
#' 
#' @param href href
#' @param type type
#' 
#' @return CustomDimension.parentLink object
#' 
#' @export
CustomDimension.parentLink <- function(href) {
    list(href = href, type = "analytics#webproperty")
}

#' CustomDimensions Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' A custom dimension collection lists Analytics custom dimensions to which the user has access. Each resource in the collection corresponds to a single Analytics custom dimension.
#' 
#' @param items items
#' @param itemsPerPage itemsPerPage
#' @param nextLink nextLink
#' @param previousLink previousLink
#' @param startIndex startIndex
#' @param totalResults totalResults
#' @param username username
#' 
#' @return CustomDimensions object
#' 
#' @export
CustomDimensions <- function(items, itemsPerPage, nextLink, previousLink, startIndex, 
    totalResults, username) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#customDimensions", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults, username = username)
}

#' CustomMetric Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for Analytics Custom Metric.
#' 
#' @param accountId accountId
#' @param active active
#' @param id id
#' @param max_value max_value
#' @param min_value min_value
#' @param name name
#' @param parentLink parentLink
#' @param scope scope
#' @param type type
#' @param webPropertyId webPropertyId
#' 
#' @return CustomMetric object
#' 
#' @export
CustomMetric <- function(accountId, active, id, max_value, min_value, name, parentLink, 
    scope, webPropertyId) {
    list(accountId = accountId, active = active, id = id, max_value = max_value, 
        min_value = min_value, name = name, parentLink = parentLink, scope = scope, 
        type = type, webPropertyId = webPropertyId)
}

#' CustomMetric.parentLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Parent link for the custom metric. Points to the property to which the custom metric belongs.
#' 
#' @param href href
#' @param type type
#' 
#' @return CustomMetric.parentLink object
#' 
#' @export
CustomMetric.parentLink <- function(href) {
    list(href = href, type = "analytics#webproperty")
}

#' CustomMetrics Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' A custom metric collection lists Analytics custom metrics to which the user has access. Each resource in the collection corresponds to a single Analytics custom metric.
#' 
#' @param items items
#' @param itemsPerPage itemsPerPage
#' @param nextLink nextLink
#' @param previousLink previousLink
#' @param startIndex startIndex
#' @param totalResults totalResults
#' @param username username
#' 
#' @return CustomMetrics object
#' 
#' @export
CustomMetrics <- function(items, itemsPerPage, nextLink, previousLink, startIndex, 
    totalResults, username) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#customMetrics", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults, username = username)
}

#' EntityAdWordsLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for Analytics Entity AdWords Link.
#' 
#' @param adWordsAccounts adWordsAccounts
#' @param entity entity
#' @param id id
#' @param name name
#' @param profileIds profileIds
#' @param selfLink selfLink
#' 
#' @return EntityAdWordsLink object
#' 
#' @export
EntityAdWordsLink <- function(adWordsAccounts, entity, id, name, profileIds, selfLink) {
    list(adWordsAccounts = adWordsAccounts, entity = entity, id = id, kind = "analytics#entityAdWordsLink", 
        name = name, profileIds = profileIds, selfLink = selfLink)
}

#' EntityAdWordsLink.entity Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Web property being linked.
#' 
#' @param webPropertyRef webPropertyRef
#' 
#' @return EntityAdWordsLink.entity object
#' 
#' @export
EntityAdWordsLink.entity <- function(webPropertyRef) {
    list(webPropertyRef = webPropertyRef)
}

#' EntityAdWordsLinks Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' An entity AdWords link collection provides a list of GA-AdWords links Each resource in this collection corresponds to a single link.
#' 
#' @param items items
#' @param itemsPerPage itemsPerPage
#' @param nextLink nextLink
#' @param previousLink previousLink
#' @param startIndex startIndex
#' @param totalResults totalResults
#' 
#' @return EntityAdWordsLinks object
#' 
#' @export
EntityAdWordsLinks <- function(items, itemsPerPage, nextLink, previousLink, startIndex, 
    totalResults) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#entityAdWordsLinks", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults)
}

#' EntityUserLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for an Analytics Entity-User Link. Returns permissions that a user has for an entity.
#' 
#' @param entity entity
#' @param id id
#' @param permissions permissions
#' @param selfLink selfLink
#' @param userRef userRef
#' 
#' @return EntityUserLink object
#' 
#' @export
EntityUserLink <- function(entity, id, permissions, selfLink, userRef) {
    list(entity = entity, id = id, kind = "analytics#entityUserLink", permissions = permissions, 
        selfLink = selfLink, userRef = userRef)
}

#' EntityUserLink.entity Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Entity for this link. It can be an account, a web property, or a view (profile).
#' 
#' @param accountRef accountRef
#' @param profileRef profileRef
#' @param webPropertyRef webPropertyRef
#' 
#' @return EntityUserLink.entity object
#' 
#' @export
EntityUserLink.entity <- function(accountRef, profileRef, webPropertyRef) {
    list(accountRef = accountRef, profileRef = profileRef, webPropertyRef = webPropertyRef)
}

#' EntityUserLink.permissions Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Permissions the user has for this entity.
#' 
#' @param local local
#' 
#' @return EntityUserLink.permissions object
#' 
#' @export
EntityUserLink.permissions <- function(local) {
    list(local = local)
}

#' EntityUserLinks Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' An entity user link collection provides a list of Analytics ACL links Each resource in this collection corresponds to a single link.
#' 
#' @param items items
#' @param itemsPerPage itemsPerPage
#' @param nextLink nextLink
#' @param previousLink previousLink
#' @param startIndex startIndex
#' @param totalResults totalResults
#' 
#' @return EntityUserLinks object
#' 
#' @export
EntityUserLinks <- function(items, itemsPerPage, nextLink, previousLink, startIndex, 
    totalResults) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#entityUserLinks", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults)
}

#' Experiment Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for Analytics experiment resource.
#' 
#' @param accountId accountId
#' @param created created
#' @param description description
#' @param editableInGaUi editableInGaUi
#' @param endTime endTime
#' @param equalWeighting equalWeighting
#' @param id id
#' @param internalWebPropertyId internalWebPropertyId
#' @param minimumExperimentLengthInDays minimumExperimentLengthInDays
#' @param name name
#' @param objectiveMetric objectiveMetric
#' @param optimizationType optimizationType
#' @param parentLink parentLink
#' @param profileId profileId
#' @param reasonExperimentEnded reasonExperimentEnded
#' @param rewriteVariationUrlsAsOriginal rewriteVariationUrlsAsOriginal
#' @param selfLink selfLink
#' @param servingFramework servingFramework
#' @param snippet snippet
#' @param startTime startTime
#' @param status status
#' @param trafficCoverage trafficCoverage
#' @param updated updated
#' @param variations variations
#' @param webPropertyId webPropertyId
#' @param winnerConfidenceLevel winnerConfidenceLevel
#' @param winnerFound winnerFound
#' 
#' @return Experiment object
#' 
#' @export
Experiment <- function(accountId, created, description, editableInGaUi, endTime, 
    equalWeighting, id, internalWebPropertyId, minimumExperimentLengthInDays, name, 
    objectiveMetric, optimizationType, parentLink, profileId, reasonExperimentEnded, 
    rewriteVariationUrlsAsOriginal, selfLink, servingFramework, snippet, startTime, 
    status, trafficCoverage, updated, variations, webPropertyId, winnerConfidenceLevel, 
    winnerFound) {
    list(accountId = accountId, created = created, description = description, editableInGaUi = editableInGaUi, 
        endTime = endTime, equalWeighting = equalWeighting, id = id, internalWebPropertyId = internalWebPropertyId, 
        kind = "analytics#experiment", minimumExperimentLengthInDays = minimumExperimentLengthInDays, 
        name = name, objectiveMetric = objectiveMetric, optimizationType = optimizationType, 
        parentLink = parentLink, profileId = profileId, reasonExperimentEnded = reasonExperimentEnded, 
        rewriteVariationUrlsAsOriginal = rewriteVariationUrlsAsOriginal, selfLink = selfLink, 
        servingFramework = servingFramework, snippet = snippet, startTime = startTime, 
        status = status, trafficCoverage = trafficCoverage, updated = updated, variations = variations, 
        webPropertyId = webPropertyId, winnerConfidenceLevel = winnerConfidenceLevel, 
        winnerFound = winnerFound)
}

#' Experiment.parentLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Parent link for an experiment. Points to the view (profile) to which this experiment belongs.
#' 
#' @param href href
#' @param type type
#' 
#' @return Experiment.parentLink object
#' 
#' @export
Experiment.parentLink <- function(href) {
    list(href = href, type = "analytics#profile")
}

#' Experiment.variations Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' No description
#' 
#' @param  
#' 
#' @return Experiment.variations object
#' 
#' @export
Experiment.variations <- function() {
    list()
}

#' Experiments Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' An experiment collection lists Analytics experiments to which the user has access. Each view (profile) can have a set of experiments. Each resource in the Experiment collection corresponds to a single Analytics experiment.
#' 
#' @param items items
#' @param itemsPerPage itemsPerPage
#' @param nextLink nextLink
#' @param previousLink previousLink
#' @param startIndex startIndex
#' @param totalResults totalResults
#' @param username username
#' 
#' @return Experiments object
#' 
#' @export
Experiments <- function(items, itemsPerPage, nextLink, previousLink, startIndex, 
    totalResults, username) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#experiments", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults, username = username)
}

#' Filter Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for an Analytics account filter.
#' 
#' @param accountId accountId
#' @param advancedDetails advancedDetails
#' @param excludeDetails excludeDetails
#' @param id id
#' @param includeDetails includeDetails
#' @param lowercaseDetails lowercaseDetails
#' @param name name
#' @param parentLink parentLink
#' @param searchAndReplaceDetails searchAndReplaceDetails
#' @param type type
#' @param uppercaseDetails uppercaseDetails
#' 
#' @return Filter object
#' 
#' @export
Filter <- function(accountId, advancedDetails, excludeDetails, id, includeDetails, 
    lowercaseDetails, name, parentLink, searchAndReplaceDetails, uppercaseDetails) {
    list(accountId = accountId, advancedDetails = advancedDetails, excludeDetails = excludeDetails, 
        id = id, includeDetails = includeDetails, lowercaseDetails = lowercaseDetails, 
        name = name, parentLink = parentLink, searchAndReplaceDetails = searchAndReplaceDetails, 
        type = type, uppercaseDetails = uppercaseDetails)
}

#' Filter.advancedDetails Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Details for the filter of the type ADVANCED.
#' 
#' @param caseSensitive caseSensitive
#' @param extractA extractA
#' @param extractB extractB
#' @param fieldA fieldA
#' @param fieldAIndex fieldAIndex
#' @param fieldARequired fieldARequired
#' @param fieldB fieldB
#' @param fieldBIndex fieldBIndex
#' @param fieldBRequired fieldBRequired
#' @param outputConstructor outputConstructor
#' @param outputToField outputToField
#' @param outputToFieldIndex outputToFieldIndex
#' @param overrideOutputField overrideOutputField
#' 
#' @return Filter.advancedDetails object
#' 
#' @export
Filter.advancedDetails <- function(caseSensitive, extractA, extractB, fieldA, fieldAIndex, 
    fieldARequired, fieldB, fieldBIndex, fieldBRequired, outputConstructor, outputToField, 
    outputToFieldIndex, overrideOutputField) {
    list(caseSensitive = caseSensitive, extractA = extractA, extractB = extractB, 
        fieldA = fieldA, fieldAIndex = fieldAIndex, fieldARequired = fieldARequired, 
        fieldB = fieldB, fieldBIndex = fieldBIndex, fieldBRequired = fieldBRequired, 
        outputConstructor = outputConstructor, outputToField = outputToField, outputToFieldIndex = outputToFieldIndex, 
        overrideOutputField = overrideOutputField)
}

#' Filter.lowercaseDetails Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Details for the filter of the type LOWER.
#' 
#' @param field field
#' @param fieldIndex fieldIndex
#' 
#' @return Filter.lowercaseDetails object
#' 
#' @export
Filter.lowercaseDetails <- function(field, fieldIndex) {
    list(field = field, fieldIndex = fieldIndex)
}

#' Filter.parentLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Parent link for this filter. Points to the account to which this filter belongs.
#' 
#' @param href href
#' @param type type
#' 
#' @return Filter.parentLink object
#' 
#' @export
Filter.parentLink <- function(href) {
    list(href = href, type = "analytics#account")
}

#' Filter.searchAndReplaceDetails Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Details for the filter of the type SEARCH_AND_REPLACE.
#' 
#' @param caseSensitive caseSensitive
#' @param field field
#' @param fieldIndex fieldIndex
#' @param replaceString replaceString
#' @param searchString searchString
#' 
#' @return Filter.searchAndReplaceDetails object
#' 
#' @export
Filter.searchAndReplaceDetails <- function(caseSensitive, field, fieldIndex, replaceString, 
    searchString) {
    list(caseSensitive = caseSensitive, field = field, fieldIndex = fieldIndex, replaceString = replaceString, 
        searchString = searchString)
}

#' Filter.uppercaseDetails Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Details for the filter of the type UPPER.
#' 
#' @param field field
#' @param fieldIndex fieldIndex
#' 
#' @return Filter.uppercaseDetails object
#' 
#' @export
Filter.uppercaseDetails <- function(field, fieldIndex) {
    list(field = field, fieldIndex = fieldIndex)
}

#' FilterExpression Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for an Analytics filter expression.
#' 
#' @param caseSensitive caseSensitive
#' @param expressionValue expressionValue
#' @param field field
#' @param fieldIndex fieldIndex
#' @param matchType matchType
#' 
#' @return FilterExpression object
#' 
#' @export
FilterExpression <- function(caseSensitive, expressionValue, field, fieldIndex, matchType) {
    list(caseSensitive = caseSensitive, expressionValue = expressionValue, field = field, 
        fieldIndex = fieldIndex, kind = "analytics#filterExpression", matchType = matchType)
}

#' FilterRef Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for a profile filter link.
#' 
#' @param href href
#' @param id id
#' 
#' @return FilterRef object
#' 
#' @export
FilterRef <- function(href, id) {
    list(href = href, id = id, kind = "analytics#filterRef")
}

#' Filters Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' A filter collection lists filters created by users in an Analytics account. Each resource in the collection corresponds to a filter.
#' 
#' @param items items
#' @param itemsPerPage itemsPerPage
#' @param nextLink nextLink
#' @param previousLink previousLink
#' @param startIndex startIndex
#' @param totalResults totalResults
#' @param username username
#' 
#' @return Filters object
#' 
#' @export
Filters <- function(items, itemsPerPage, nextLink, previousLink, startIndex, totalResults, 
    username) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#filters", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults, username = username)
}

#' GaData Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Analytics data for a given view (profile).
#' 
#' @param columnHeaders columnHeaders
#' @param containsSampledData containsSampledData
#' @param dataTable dataTable
#' @param id id
#' @param itemsPerPage itemsPerPage
#' @param nextLink nextLink
#' @param previousLink previousLink
#' @param profileInfo profileInfo
#' @param query query
#' @param rows rows
#' @param sampleSize sampleSize
#' @param sampleSpace sampleSpace
#' @param selfLink selfLink
#' @param totalResults totalResults
#' @param totalsForAllResults totalsForAllResults
#' 
#' @return GaData object
#' 
#' @export
GaData <- function(columnHeaders, containsSampledData, dataTable, id, itemsPerPage, 
    nextLink, previousLink, profileInfo, query, rows, sampleSize, sampleSpace, selfLink, 
    totalResults, totalsForAllResults) {
    list(columnHeaders = columnHeaders, containsSampledData = containsSampledData, 
        dataTable = dataTable, id = id, itemsPerPage = itemsPerPage, kind = "analytics#gaData", 
        nextLink = nextLink, previousLink = previousLink, profileInfo = profileInfo, 
        query = query, rows = rows, sampleSize = sampleSize, sampleSpace = sampleSpace, 
        selfLink = selfLink, totalResults = totalResults, totalsForAllResults = totalsForAllResults)
}

#' GaData.columnHeaders Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' No description
#' 
#' @param  
#' 
#' @return GaData.columnHeaders object
#' 
#' @export
GaData.columnHeaders <- function() {
    list()
}

#' GaData.dataTable Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' No description
#' 
#' @param cols cols
#' @param rows rows
#' 
#' @return GaData.dataTable object
#' 
#' @export
GaData.dataTable <- function(cols, rows) {
    list(cols = cols, rows = rows)
}

#' GaData.dataTable.cols Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' No description
#' 
#' @param  
#' 
#' @return GaData.dataTable.cols object
#' 
#' @export
GaData.dataTable.cols <- function() {
    list()
}

#' GaData.dataTable.rows Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' No description
#' 
#' @param  
#' 
#' @return GaData.dataTable.rows object
#' 
#' @export
GaData.dataTable.rows <- function() {
    list()
}

#' GaData.dataTable.rows.c Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' No description
#' 
#' @param  
#' 
#' @return GaData.dataTable.rows.c object
#' 
#' @export
GaData.dataTable.rows.c <- function() {
    list()
}

#' GaData.profileInfo Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Information for the view (profile), for which the Analytics data was requested.
#' 
#' @param accountId accountId
#' @param internalWebPropertyId internalWebPropertyId
#' @param profileId profileId
#' @param profileName profileName
#' @param tableId tableId
#' @param webPropertyId webPropertyId
#' 
#' @return GaData.profileInfo object
#' 
#' @export
GaData.profileInfo <- function(accountId, internalWebPropertyId, profileId, profileName, 
    tableId, webPropertyId) {
    list(accountId = accountId, internalWebPropertyId = internalWebPropertyId, profileId = profileId, 
        profileName = profileName, tableId = tableId, webPropertyId = webPropertyId)
}

#' GaData.query Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Analytics data request query parameters.
#' 
#' @param dimensions dimensions
#' @param end-date end-date
#' @param filters filters
#' @param ids ids
#' @param max-results max-results
#' @param metrics metrics
#' @param samplingLevel samplingLevel
#' @param segment segment
#' @param sort sort
#' @param start-date start-date
#' @param start-index start-index
#' 
#' @return GaData.query object
#' 
#' @export
GaData.query <- function(dimensions, end.date, filters, ids, max.results, metrics, 
    samplingLevel, segment, sort, start.date, start.index) {
    list(dimensions = dimensions, `end-date` = end - date, filters = filters, ids = ids, 
        `max-results` = max - results, metrics = metrics, samplingLevel = samplingLevel, 
        segment = segment, sort = sort, `start-date` = start - date, `start-index` = start - 
            index)
}

#' GaData.totalsForAllResults Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Total values for the requested metrics over all the results, not just the results returned in this response. The order of the metric totals is same as the metric order specified in the request.
#' 
#' @param  
#' 
#' @return GaData.totalsForAllResults object
#' 
#' @export
GaData.totalsForAllResults <- function() {
    list()
}

#' Goal Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for Analytics goal resource.
#' 
#' @param accountId accountId
#' @param active active
#' @param created created
#' @param eventDetails eventDetails
#' @param id id
#' @param internalWebPropertyId internalWebPropertyId
#' @param name name
#' @param parentLink parentLink
#' @param profileId profileId
#' @param selfLink selfLink
#' @param type type
#' @param updated updated
#' @param urlDestinationDetails urlDestinationDetails
#' @param value value
#' @param visitNumPagesDetails visitNumPagesDetails
#' @param visitTimeOnSiteDetails visitTimeOnSiteDetails
#' @param webPropertyId webPropertyId
#' 
#' @return Goal object
#' 
#' @export
Goal <- function(accountId, active, created, eventDetails, id, internalWebPropertyId, 
    name, parentLink, profileId, selfLink, updated, urlDestinationDetails, value, 
    visitNumPagesDetails, visitTimeOnSiteDetails, webPropertyId) {
    list(accountId = accountId, active = active, created = created, eventDetails = eventDetails, 
        id = id, internalWebPropertyId = internalWebPropertyId, kind = "analytics#goal", 
        name = name, parentLink = parentLink, profileId = profileId, selfLink = selfLink, 
        type = type, updated = updated, urlDestinationDetails = urlDestinationDetails, 
        value = value, visitNumPagesDetails = visitNumPagesDetails, visitTimeOnSiteDetails = visitTimeOnSiteDetails, 
        webPropertyId = webPropertyId)
}

#' Goal.eventDetails Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Details for the goal of the type EVENT.
#' 
#' @param eventConditions eventConditions
#' @param useEventValue useEventValue
#' 
#' @return Goal.eventDetails object
#' 
#' @export
Goal.eventDetails <- function(eventConditions, useEventValue) {
    list(eventConditions = eventConditions, useEventValue = useEventValue)
}

#' Goal.eventDetails.eventConditions Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' No description
#' 
#' @param  
#' 
#' @return Goal.eventDetails.eventConditions object
#' 
#' @export
Goal.eventDetails.eventConditions <- function() {
    list()
}

#' Goal.parentLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Parent link for a goal. Points to the view (profile) to which this goal belongs.
#' 
#' @param href href
#' @param type type
#' 
#' @return Goal.parentLink object
#' 
#' @export
Goal.parentLink <- function(href) {
    list(href = href, type = "analytics#profile")
}

#' Goal.urlDestinationDetails Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Details for the goal of the type URL_DESTINATION.
#' 
#' @param caseSensitive caseSensitive
#' @param firstStepRequired firstStepRequired
#' @param matchType matchType
#' @param steps steps
#' @param url url
#' 
#' @return Goal.urlDestinationDetails object
#' 
#' @export
Goal.urlDestinationDetails <- function(caseSensitive, firstStepRequired, matchType, 
    steps, url) {
    list(caseSensitive = caseSensitive, firstStepRequired = firstStepRequired, matchType = matchType, 
        steps = steps, url = url)
}

#' Goal.urlDestinationDetails.steps Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' No description
#' 
#' @param  
#' 
#' @return Goal.urlDestinationDetails.steps object
#' 
#' @export
Goal.urlDestinationDetails.steps <- function() {
    list()
}

#' Goal.visitNumPagesDetails Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Details for the goal of the type VISIT_NUM_PAGES.
#' 
#' @param comparisonType comparisonType
#' @param comparisonValue comparisonValue
#' 
#' @return Goal.visitNumPagesDetails object
#' 
#' @export
Goal.visitNumPagesDetails <- function(comparisonType, comparisonValue) {
    list(comparisonType = comparisonType, comparisonValue = comparisonValue)
}

#' Goal.visitTimeOnSiteDetails Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Details for the goal of the type VISIT_TIME_ON_SITE.
#' 
#' @param comparisonType comparisonType
#' @param comparisonValue comparisonValue
#' 
#' @return Goal.visitTimeOnSiteDetails object
#' 
#' @export
Goal.visitTimeOnSiteDetails <- function(comparisonType, comparisonValue) {
    list(comparisonType = comparisonType, comparisonValue = comparisonValue)
}

#' Goals Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' A goal collection lists Analytics goals to which the user has access. Each view (profile) can have a set of goals. Each resource in the Goal collection corresponds to a single Analytics goal.
#' 
#' @param items items
#' @param itemsPerPage itemsPerPage
#' @param nextLink nextLink
#' @param previousLink previousLink
#' @param startIndex startIndex
#' @param totalResults totalResults
#' @param username username
#' 
#' @return Goals object
#' 
#' @export
Goals <- function(items, itemsPerPage, nextLink, previousLink, startIndex, totalResults, 
    username) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#goals", nextLink = nextLink, 
        previousLink = previousLink, startIndex = startIndex, totalResults = totalResults, 
        username = username)
}

#' McfData Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Multi-Channel Funnels data for a given view (profile).
#' 
#' @param columnHeaders columnHeaders
#' @param containsSampledData containsSampledData
#' @param id id
#' @param itemsPerPage itemsPerPage
#' @param nextLink nextLink
#' @param previousLink previousLink
#' @param profileInfo profileInfo
#' @param query query
#' @param rows rows
#' @param sampleSize sampleSize
#' @param sampleSpace sampleSpace
#' @param selfLink selfLink
#' @param totalResults totalResults
#' @param totalsForAllResults totalsForAllResults
#' 
#' @return McfData object
#' 
#' @export
McfData <- function(columnHeaders, containsSampledData, id, itemsPerPage, nextLink, 
    previousLink, profileInfo, query, rows, sampleSize, sampleSpace, selfLink, totalResults, 
    totalsForAllResults) {
    list(columnHeaders = columnHeaders, containsSampledData = containsSampledData, 
        id = id, itemsPerPage = itemsPerPage, kind = "analytics#mcfData", nextLink = nextLink, 
        previousLink = previousLink, profileInfo = profileInfo, query = query, rows = rows, 
        sampleSize = sampleSize, sampleSpace = sampleSpace, selfLink = selfLink, 
        totalResults = totalResults, totalsForAllResults = totalsForAllResults)
}

#' McfData.columnHeaders Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' No description
#' 
#' @param  
#' 
#' @return McfData.columnHeaders object
#' 
#' @export
McfData.columnHeaders <- function() {
    list()
}

#' McfData.profileInfo Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Information for the view (profile), for which the Analytics data was requested.
#' 
#' @param accountId accountId
#' @param internalWebPropertyId internalWebPropertyId
#' @param profileId profileId
#' @param profileName profileName
#' @param tableId tableId
#' @param webPropertyId webPropertyId
#' 
#' @return McfData.profileInfo object
#' 
#' @export
McfData.profileInfo <- function(accountId, internalWebPropertyId, profileId, profileName, 
    tableId, webPropertyId) {
    list(accountId = accountId, internalWebPropertyId = internalWebPropertyId, profileId = profileId, 
        profileName = profileName, tableId = tableId, webPropertyId = webPropertyId)
}

#' McfData.query Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Analytics data request query parameters.
#' 
#' @param dimensions dimensions
#' @param end-date end-date
#' @param filters filters
#' @param ids ids
#' @param max-results max-results
#' @param metrics metrics
#' @param samplingLevel samplingLevel
#' @param segment segment
#' @param sort sort
#' @param start-date start-date
#' @param start-index start-index
#' 
#' @return McfData.query object
#' 
#' @export
McfData.query <- function(dimensions, end.date, filters, ids, max.results, metrics, 
    samplingLevel, segment, sort, start.date, start.index) {
    list(dimensions = dimensions, `end-date` = end - date, filters = filters, ids = ids, 
        `max-results` = max - results, metrics = metrics, samplingLevel = samplingLevel, 
        segment = segment, sort = sort, `start-date` = start - date, `start-index` = start - 
            index)
}

#' McfData.totalsForAllResults Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Total values for the requested metrics over all the results, not just the results returned in this response. The order of the metric totals is same as the metric order specified in the request.
#' 
#' @param  
#' 
#' @return McfData.totalsForAllResults object
#' 
#' @export
McfData.totalsForAllResults <- function() {
    list()
}

#' Profile Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for an Analytics view (profile).
#' 
#' @param accountId accountId
#' @param botFilteringEnabled botFilteringEnabled
#' @param childLink childLink
#' @param currency currency
#' @param defaultPage defaultPage
#' @param eCommerceTracking eCommerceTracking
#' @param enhancedECommerceTracking enhancedECommerceTracking
#' @param excludeQueryParameters excludeQueryParameters
#' @param id id
#' @param name name
#' @param parentLink parentLink
#' @param permissions permissions
#' @param siteSearchCategoryParameters siteSearchCategoryParameters
#' @param siteSearchQueryParameters siteSearchQueryParameters
#' @param starred starred
#' @param stripSiteSearchCategoryParameters stripSiteSearchCategoryParameters
#' @param stripSiteSearchQueryParameters stripSiteSearchQueryParameters
#' @param timezone timezone
#' @param type type
#' @param websiteUrl websiteUrl
#' 
#' @return Profile object
#' 
#' @export
Profile <- function(accountId, botFilteringEnabled, childLink, currency, defaultPage, 
    eCommerceTracking, enhancedECommerceTracking, excludeQueryParameters, id, name, 
    parentLink, permissions, siteSearchCategoryParameters, siteSearchQueryParameters, 
    starred, stripSiteSearchCategoryParameters, stripSiteSearchQueryParameters, timezone, 
    websiteUrl) {
    list(accountId = accountId, botFilteringEnabled = botFilteringEnabled, childLink = childLink, 
        currency = currency, defaultPage = defaultPage, eCommerceTracking = eCommerceTracking, 
        enhancedECommerceTracking = enhancedECommerceTracking, excludeQueryParameters = excludeQueryParameters, 
        id = id, name = name, parentLink = parentLink, permissions = permissions, 
        siteSearchCategoryParameters = siteSearchCategoryParameters, siteSearchQueryParameters = siteSearchQueryParameters, 
        starred = starred, stripSiteSearchCategoryParameters = stripSiteSearchCategoryParameters, 
        stripSiteSearchQueryParameters = stripSiteSearchQueryParameters, timezone = timezone, 
        type = type, websiteUrl = websiteUrl)
}

#' Profile.childLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Child link for this view (profile). Points to the list of goals for this view (profile).
#' 
#' @param href href
#' @param type type
#' 
#' @return Profile.childLink object
#' 
#' @export
Profile.childLink <- function(href) {
    list(href = href, type = "analytics#goals")
}

#' Profile.parentLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Parent link for this view (profile). Points to the web property to which this view (profile) belongs.
#' 
#' @param href href
#' @param type type
#' 
#' @return Profile.parentLink object
#' 
#' @export
Profile.parentLink <- function(href) {
    list(href = href, type = "analytics#webproperty")
}

#' Profile.permissions Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Permissions the user has for this view (profile).
#' 
#' @param  
#' 
#' @return Profile.permissions object
#' 
#' @export
Profile.permissions <- function() {
    list()
}

#' ProfileFilterLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for an Analytics profile filter link.
#' 
#' @param filterRef filterRef
#' @param id id
#' @param profileRef profileRef
#' @param rank rank
#' 
#' @return ProfileFilterLink object
#' 
#' @export
ProfileFilterLink <- function(filterRef, id, profileRef, rank) {
    list(filterRef = filterRef, id = id, profileRef = profileRef, rank = rank)
}

#' ProfileFilterLinks Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' A profile filter link collection lists profile filter links between profiles and filters. Each resource in the collection corresponds to a profile filter link.
#' 
#' @param items items
#' @param itemsPerPage itemsPerPage
#' @param nextLink nextLink
#' @param previousLink previousLink
#' @param startIndex startIndex
#' @param totalResults totalResults
#' @param username username
#' 
#' @return ProfileFilterLinks object
#' 
#' @export
ProfileFilterLinks <- function(items, itemsPerPage, nextLink, previousLink, startIndex, 
    totalResults, username) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#profileFilterLinks", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults, username = username)
}

#' ProfileRef Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for a linked view (profile).
#' 
#' @param accountId accountId
#' @param href href
#' @param id id
#' @param internalWebPropertyId internalWebPropertyId
#' @param name name
#' @param webPropertyId webPropertyId
#' 
#' @return ProfileRef object
#' 
#' @export
ProfileRef <- function(accountId, href, id, internalWebPropertyId, name, webPropertyId) {
    list(accountId = accountId, href = href, id = id, internalWebPropertyId = internalWebPropertyId, 
        kind = "analytics#profileRef", name = name, webPropertyId = webPropertyId)
}

#' ProfileSummary Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for an Analytics ProfileSummary. ProfileSummary returns basic information (i.e., summary) for a profile.
#' 
#' @param id id
#' @param name name
#' @param starred starred
#' @param type type
#' 
#' @return ProfileSummary object
#' 
#' @export
ProfileSummary <- function(id, name, starred) {
    list(id = id, kind = "analytics#profileSummary", name = name, starred = starred, 
        type = type)
}

#' Profiles Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' A view (profile) collection lists Analytics views (profiles) to which the user has access. Each resource in the collection corresponds to a single Analytics view (profile).
#' 
#' @param items items
#' @param itemsPerPage itemsPerPage
#' @param nextLink nextLink
#' @param previousLink previousLink
#' @param startIndex startIndex
#' @param totalResults totalResults
#' @param username username
#' 
#' @return Profiles object
#' 
#' @export
Profiles <- function(items, itemsPerPage, nextLink, previousLink, startIndex, totalResults, 
    username) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#profiles", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults, username = username)
}

#' RealtimeData Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Real time data for a given view (profile).
#' 
#' @param columnHeaders columnHeaders
#' @param id id
#' @param profileInfo profileInfo
#' @param query query
#' @param rows rows
#' @param selfLink selfLink
#' @param totalResults totalResults
#' @param totalsForAllResults totalsForAllResults
#' 
#' @return RealtimeData object
#' 
#' @export
RealtimeData <- function(columnHeaders, id, profileInfo, query, rows, selfLink, totalResults, 
    totalsForAllResults) {
    list(columnHeaders = columnHeaders, id = id, kind = "analytics#realtimeData", 
        profileInfo = profileInfo, query = query, rows = rows, selfLink = selfLink, 
        totalResults = totalResults, totalsForAllResults = totalsForAllResults)
}

#' RealtimeData.columnHeaders Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' No description
#' 
#' @param  
#' 
#' @return RealtimeData.columnHeaders object
#' 
#' @export
RealtimeData.columnHeaders <- function() {
    list()
}

#' RealtimeData.profileInfo Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Information for the view (profile), for which the real time data was requested.
#' 
#' @param accountId accountId
#' @param internalWebPropertyId internalWebPropertyId
#' @param profileId profileId
#' @param profileName profileName
#' @param tableId tableId
#' @param webPropertyId webPropertyId
#' 
#' @return RealtimeData.profileInfo object
#' 
#' @export
RealtimeData.profileInfo <- function(accountId, internalWebPropertyId, profileId, 
    profileName, tableId, webPropertyId) {
    list(accountId = accountId, internalWebPropertyId = internalWebPropertyId, profileId = profileId, 
        profileName = profileName, tableId = tableId, webPropertyId = webPropertyId)
}

#' RealtimeData.query Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Real time data request query parameters.
#' 
#' @param dimensions dimensions
#' @param filters filters
#' @param ids ids
#' @param max-results max-results
#' @param metrics metrics
#' @param sort sort
#' 
#' @return RealtimeData.query object
#' 
#' @export
RealtimeData.query <- function(dimensions, filters, ids, max.results, metrics, sort) {
    list(dimensions = dimensions, filters = filters, ids = ids, `max-results` = max - 
        results, metrics = metrics, sort = sort)
}

#' RealtimeData.totalsForAllResults Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Total values for the requested metrics over all the results, not just the results returned in this response. The order of the metric totals is same as the metric order specified in the request.
#' 
#' @param  
#' 
#' @return RealtimeData.totalsForAllResults object
#' 
#' @export
RealtimeData.totalsForAllResults <- function() {
    list()
}

#' Segment Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for an Analytics segment.
#' 
#' @param created created
#' @param definition definition
#' @param id id
#' @param name name
#' @param segmentId segmentId
#' @param selfLink selfLink
#' @param type type
#' @param updated updated
#' 
#' @return Segment object
#' 
#' @export
Segment <- function(created, definition, id, name, segmentId, selfLink, updated) {
    list(created = created, definition = definition, id = id, kind = "analytics#segment", 
        name = name, segmentId = segmentId, selfLink = selfLink, type = type, updated = updated)
}

#' Segments Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' An segment collection lists Analytics segments that the user has access to. Each resource in the collection corresponds to a single Analytics segment.
#' 
#' @param items items
#' @param itemsPerPage itemsPerPage
#' @param nextLink nextLink
#' @param previousLink previousLink
#' @param startIndex startIndex
#' @param totalResults totalResults
#' @param username username
#' 
#' @return Segments object
#' 
#' @export
Segments <- function(items, itemsPerPage, nextLink, previousLink, startIndex, totalResults, 
    username) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#segments", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults, username = username)
}

#' UnsampledReport Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for Analytics unsampled report resource.
#' 
#' @param accountId accountId
#' @param dimensions dimensions
#' @param end-date end-date
#' @param filters filters
#' @param id id
#' @param metrics metrics
#' @param profileId profileId
#' @param segment segment
#' @param start-date start-date
#' @param title title
#' @param webPropertyId webPropertyId
#' 
#' @return UnsampledReport object
#' 
#' @export
UnsampledReport <- function(accountId, dimensions, end.date, filters, id, metrics, 
    profileId, segment, start.date, title, webPropertyId) {
    list(accountId = accountId, dimensions = dimensions, `end-date` = end - date, 
        filters = filters, id = id, metrics = metrics, profileId = profileId, segment = segment, 
        `start-date` = start - date, title = title, webPropertyId = webPropertyId)
}

#' UnsampledReport.cloudStorageDownloadDetails Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Download details for a file stored in Google Cloud Storage.
#' 
#' @param bucketId bucketId
#' @param objectId objectId
#' 
#' @return UnsampledReport.cloudStorageDownloadDetails object
#' 
#' @export
UnsampledReport.cloudStorageDownloadDetails <- function(bucketId, objectId) {
    list(bucketId = bucketId, objectId = objectId)
}

#' UnsampledReport.driveDownloadDetails Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Download details for a file stored in Google Drive.
#' 
#' @param documentId documentId
#' 
#' @return UnsampledReport.driveDownloadDetails object
#' 
#' @export
UnsampledReport.driveDownloadDetails <- function(documentId) {
    list(documentId = documentId)
}

#' UnsampledReports Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' An unsampled report collection lists Analytics unsampled reports to which the user has access. Each view (profile) can have a set of unsampled reports. Each resource in the unsampled report collection corresponds to a single Analytics unsampled report.
#' 
#' @param items items
#' @param itemsPerPage itemsPerPage
#' @param nextLink nextLink
#' @param previousLink previousLink
#' @param startIndex startIndex
#' @param totalResults totalResults
#' @param username username
#' 
#' @return UnsampledReports object
#' 
#' @export
UnsampledReports <- function(items, itemsPerPage, nextLink, previousLink, startIndex, 
    totalResults, username) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#unsampledReports", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults, username = username)
}

#' Upload Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Metadata returned for an upload operation.
#' 
#' @param accountId accountId
#' @param customDataSourceId customDataSourceId
#' @param errors errors
#' @param id id
#' @param status status
#' 
#' @return Upload object
#' 
#' @export
Upload <- function(accountId, customDataSourceId, errors, id, status) {
    list(accountId = accountId, customDataSourceId = customDataSourceId, errors = errors, 
        id = id, kind = "analytics#upload", status = status)
}

#' Uploads Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Upload collection lists Analytics uploads to which the user has access. Each custom data source can have a set of uploads. Each resource in the upload collection corresponds to a single Analytics data upload.
#' 
#' @param items items
#' @param itemsPerPage itemsPerPage
#' @param nextLink nextLink
#' @param previousLink previousLink
#' @param startIndex startIndex
#' @param totalResults totalResults
#' 
#' @return Uploads object
#' 
#' @export
Uploads <- function(items, itemsPerPage, nextLink, previousLink, startIndex, totalResults) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#uploads", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults)
}

#' UserRef Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for a user reference.
#' 
#' @param email email
#' @param id id
#' 
#' @return UserRef object
#' 
#' @export
UserRef <- function(email, id) {
    list(email = email, id = id, kind = "analytics#userRef")
}

#' WebPropertyRef Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for a web property reference.
#' 
#' @param accountId accountId
#' @param href href
#' @param id id
#' @param internalWebPropertyId internalWebPropertyId
#' @param name name
#' 
#' @return WebPropertyRef object
#' 
#' @export
WebPropertyRef <- function(accountId, href, id, internalWebPropertyId, name) {
    list(accountId = accountId, href = href, id = id, internalWebPropertyId = internalWebPropertyId, 
        kind = "analytics#webPropertyRef", name = name)
}

#' WebPropertySummary Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for an Analytics WebPropertySummary. WebPropertySummary returns basic information (i.e., summary) for a web property.
#' 
#' @param id id
#' @param internalWebPropertyId internalWebPropertyId
#' @param level level
#' @param name name
#' @param profiles profiles
#' @param starred starred
#' @param websiteUrl websiteUrl
#' 
#' @return WebPropertySummary object
#' 
#' @export
WebPropertySummary <- function(id, internalWebPropertyId, level, name, profiles, 
    starred, websiteUrl) {
    list(id = id, internalWebPropertyId = internalWebPropertyId, kind = "analytics#webPropertySummary", 
        level = level, name = name, profiles = profiles, starred = starred, websiteUrl = websiteUrl)
}

#' Webproperties Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' A web property collection lists Analytics web properties to which the user has access. Each resource in the collection corresponds to a single Analytics web property.
#' 
#' @param items items
#' @param itemsPerPage itemsPerPage
#' @param nextLink nextLink
#' @param previousLink previousLink
#' @param startIndex startIndex
#' @param totalResults totalResults
#' @param username username
#' 
#' @return Webproperties object
#' 
#' @export
Webproperties <- function(items, itemsPerPage, nextLink, previousLink, startIndex, 
    totalResults, username) {
    list(items = items, itemsPerPage = itemsPerPage, kind = "analytics#webproperties", 
        nextLink = nextLink, previousLink = previousLink, startIndex = startIndex, 
        totalResults = totalResults, username = username)
}

#' Webproperty Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' JSON template for an Analytics web property.
#' 
#' @param accountId accountId
#' @param childLink childLink
#' @param defaultProfileId defaultProfileId
#' @param id id
#' @param industryVertical industryVertical
#' @param name name
#' @param parentLink parentLink
#' @param permissions permissions
#' @param starred starred
#' @param websiteUrl websiteUrl
#' 
#' @return Webproperty object
#' 
#' @export
Webproperty <- function(accountId, childLink, defaultProfileId, id, industryVertical, 
    name, parentLink, permissions, starred, websiteUrl) {
    list(accountId = accountId, childLink = childLink, defaultProfileId = defaultProfileId, 
        id = id, industryVertical = industryVertical, name = name, parentLink = parentLink, 
        permissions = permissions, starred = starred, websiteUrl = websiteUrl)
}

#' Webproperty.childLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Child link for this web property. Points to the list of views (profiles) for this web property.
#' 
#' @param href href
#' @param type type
#' 
#' @return Webproperty.childLink object
#' 
#' @export
Webproperty.childLink <- function(href) {
    list(href = href, type = "analytics#profiles")
}

#' Webproperty.parentLink Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Parent link for this web property. Points to the account to which this web property belongs.
#' 
#' @param href href
#' @param type type
#' 
#' @return Webproperty.parentLink object
#' 
#' @export
Webproperty.parentLink <- function(href) {
    list(href = href, type = "analytics#account")
}


#' Webproperty.permissions Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_object}}
#' Permissions the user has for this web property.
#' 
#' @param  
#' 
#' @return Webproperty.permissions object
#' 
#' @export


Webproperty.permissions <- function() {
    
    
    
    list()
    
}

