#' Get a list of Google API libraries
#' 
#' Doesn't require authentication
#' 
#' @seealso \href{https://developers.google.com/discovery/v1/reference/apis/list}
#' 
#' @return List of Google APIs and their resources
#' @export
gar_discovery_apis_list <- function(){
  
  url <- "https://www.googleapis.com/discovery/v1/apis"
  req <- httr::RETRY("GET", url)
  
  httr::stop_for_status(req)
  
  stuff <- httr::content(req, as = "text")
  apis <- jsonlite::fromJSON(stuff)
  
  if(!is.null(apis$kind) && apis$kind == "discovery#directoryList"){
    out <- apis$items
  } else {
    stop("Problem fetching Discovery APIs")
  }
  
  out
}

#' Get meta data details for specified Google API
#' 
#' Doesn't require authentication
#' 
#' @param api The API to fetch
#' @param version The API version to fetch
#' 
#' @seealso \href{https://developers.google.com/discovery/v1/reference/apis/getRest}
#' 
#' @return Details of the API 
#' @export
gar_discovery_api <- function(api, version){
  
  url <- sprintf("https://www.googleapis.com/discovery/v1/apis/%s/%s/rest",
                 api,
                 version)
  
  req <- httr::RETRY("GET", url)
  
  httr::stop_for_status(req)
  
  stuff <- httr::content(req, as = "text")
  api <- jsonlite::fromJSON(stuff)
  
  if(!is.null(api$kind) && api$kind == "discovery#restDescription"){
    out <- api
  } else {
    stop("Problem fetching API Description")
  }
  
  out
}



#' Create an API library skeleton
#' 
#' This will create a file with the skeleton of the API functions 
#'   for the specified library
#' 
#' @param filename R file to write skeleton to
#' @param api_json The json from \link{gar_discovery_api}
#' 
#' @return TRUE if successful, side effect will write a file
#' @export
gar_create_api_skeleton <- function(filename = "./inst/new_api.R", 
                                    api_json = gar_discovery_api("urlshortener","v1")
                                    ){
  

  if(is.null(api_json$kind) && api_json$kind != "discovery#restDescription"){
    stop("api_json not recognised from gar_discovery_api")
  }
  
  if(file.exists(filename)){
    stop("File: ", filename, " exists. Delete it and run again")
  }
  
  temp <- tempfile()
  on.exit(file.remove(temp))
  
  header <- paste0(
      "#' ", api_json$title, "\n",
      "#' ", api_json$description, "\n",
      "#' \n",
      "#' Auto-generated code by googleAuthR::gar_create_api_skeleton\n",
      "#'  at ", as.character(Sys.time()), "\n",
      "#' filename: ", substitute(filename),"\n",
      "#' api_json: ", paste(substitute(api_json), collapse = " "),"\n",
      "#' \n",
      "#' @details \n",
      "#' Authentication scopes used are:\n",
      "#' \\itemize{\n",
      "#'   \\item ", paste(names(api_json$auth$oauth2$scopes), collapse = "\n#' \\item "),
      "\n#' }\n",
      "#' \n",
      "#' @docType package \n",
      "#' @name ", paste0(api_json$name,"_googleAuthR"), "\n",
      "#' \n",
      "NULL",
      "\n"
      )
  
  add_line(header, temp)
  
  ## apis can have methods at varying steps into JSON tree
  ## find the methods to extract into API
  api_method <- get_json_methods(api_json$resources)

  fd <- lapply(api_method, function_docs, api_json = api_json)
  fp <- lapply(api_method, function_params, api_json = api_json)
  fb <- lapply(api_method, function_body, api_json = api_json)

  lapply(paste(fd, fp,fb, sep = "\n\n"), add_line, temp)
  
  formatR::tidy_eval(temp, file = filename, width.cutoff = 80)
  
}



function_docs <- function(api_json_resource_method, api_json){
  
  order_names <- c(api_json_resource_method$parameterOrder, 
                   setdiff(names(api_json_resource_method$parameters), api_json_resource_method$parameterOrder))
  ordered_method_parameters <- api_json_resource_method$parameters[order_names]
  
  params <- paste(collapse = "\n#' ", sep = "\n#'",
                  lapply(names(ordered_method_parameters), 
                         make_vars_description, 
                         api_json_resource_method=ordered_method_parameters)
  )
  
  ## add api objects
  if(!is.null(api_json_resource_method$request)){
    object_param_line <- paste0("#' @param ", 
                                api_json_resource_method$request[['$ref']], 
                                " ",
                                "The \\link{",api_json_resource_method$request[['$ref']],"} object to pass to this method\n")
  } else {
    object_param_line <- NULL
  }
  
  docs <- paste0(
    "\t\n\n",
    "#' ", api_json_resource_method$description, "\n",
    "#' \n",
    "#' Autogenerated via \\code{\\link[googleAuthR]{gar_create_api_skeleton}}\n",
    "#' \n",
    "#' @seealso \\href{",api_json$documentationLink,"}{Google Documentation}\n",
    "#' \n",
    "#' @details \n",
    "#' Authentication scopes used by this function are:\n",
    "#' \\itemize{\n",
    "#'   \\item ", paste(api_json_resource_method$scopes, collapse = "\n#' \\item "),
    "\n#' }\n",
    "#' \n",
    "#' Set \\code{options(googleAuthR.scopes.selected = c(",paste(api_json_resource_method$scopes, collapse = ", "),")}\n",
    "#' Then run \\code{googleAuthR::gar_auth()} to authenticate.\n",
    "#' See \\code{\\link[googleAuthR]{gar_auth}} for details. \n",
    "#' \n",
    object_param_line,
    "#' ", params,
    "#' @importFrom googleAuthR gar_api_generator\n",
    "#' @export\n"
  )
  
  docs
}



object_docs <- function(properties_name, properties){
  
  prop <- properties[[properties_name]]
  
  if("description_api" %in% names(prop)){
    api_desc <- prop[["description_api"]]
  } else {
    api_desc <- "No description"
  }
  
  if(length(prop$description) > 0 && nchar(prop$description[[1]]) > 0){
    ## First sentence only
    # browser()
    param_description <- first_sentence(prop$description)
  } else {
    param_description <- NULL
  }
  
  message(properties_name)

  docs <- paste0(
    "\t\n\n",
    "#' ", properties_name, " Object\n",
    "#' \n",
    "#' @details \n",
    "#' Autogenerated via \\code{\\link[googleAuthR]{gar_create_api_object}}\n",
    "#' ", api_desc, "\n",
    "#' \n",
    "#' ", paste(collapse = "\n#' ", sep = "\n#'",
                 paste("@param", 
                       setdiff(names(prop[["value"]]), c("description_api","kind","type")),
                       ## First sentence only
                       param_description
                 )
            ),
    "\n",
    "#' \n",
    "#' @return ", properties_name, " object\n",
    "#' \n",
    "#' @export\n"
  )
  
  docs
}

function_params <- function(api_json_resource_method, api_json){
  
  order_names <- c(api_json_resource_method$parameterOrder, 
                   setdiff(names(api_json_resource_method$parameters), api_json_resource_method$parameterOrder))
  ordered_method_parameters <- api_json_resource_method$parameters[order_names]
  
  ## add api objects
  if(!is.null(api_json_resource_method$request)){
    object_param_var <- api_json_resource_method$request[['$ref']]
    object_list <- list(list(name = object_param_var, required = TRUE))
    names(object_list) <- object_param_var
    ordered_method_parameters <- c(object_list, 
                                   ordered_method_parameters)
  }
  
  f_name <- gsub(paste0(api_json$name,"."), "", api_json_resource_method$id)
  make_f_arguments(f_name, ordered_method_parameters)
  
  
}

object_params <- function(properties_object_name, properties_object){
  arg_names <- properties_object[[properties_object_name]]$value
  make_f_arguments(properties_object_name, arg_names, exclude = c("description_api","kind","type"))
}

function_body <- function(api_json_resource_method, api_json){
  
  pars_list <- make_pars_list(api_json_resource_method)
  
  api_url <- make_api_url_string(api_json_resource_method, api_json)
    
  fb <- paste0(
    api_url,
    "# ", api_json_resource_method$id,"\n",
    "f <- gar_api_generator(url, \n",
    "'",api_json_resource_method$httpMethod,"',\t\n",
    pars_list,
    "data_parse_function = function(x) x)\n\n",
    "f()",
    "\n",
    "}\n\n\n"
  )
  
  fb
  
}

object_body <- function(properties_name, properties){
  
  prop <- properties[[properties_name]]$value
  
  prop <- vapply(names(prop), function(x) if(prop[[x]] == "") x else paste0('"',prop[[x]],'"'), character(1))
  
  if(length(prop) == 0 ) return("list()\n\n}\n")
  
  paste("\n\nlist(", 
        paste(paste0("`",names(prop),"`"),
              prop,
              sep = " = ",
              collapse = ",\n"), 
        ")\n\n}\n\n")
}


#' Create the API objects from the Discovery API
#' 
#' @param filename File to write the objects to
#' @param api_json The json from \link{gar_discovery_api}
#' 
#' @return TRUE if successful, side-effect creating filename
#' @export
gar_create_api_objects <- function(filename = "./inst/api_objects.R", api_json){
  
  if(is.null(api_json$kind) && api_json$kind != "discovery#restDescription"){
    stop("api_json not recognised from gar_discovery_api")
  }
  
  if(file.exists(filename)){
    stop("File: ", filename, " exists. Delete it and run again")
  }
  
  temp <- tempfile()
  on.exit(file.remove(temp))
  # temp <- filename
  
  header <- paste0(
    "#' ", api_json$title, " Objects \n",
    "#' ", api_json$description, "\n",
    "#' \n",
    "#' Auto-generated code by googleAuthR::gar_create_api_objects\n",
    "#'  at ", as.character(Sys.time()), "\n",
    "#' filename: ", substitute(filename),"\n",
    "#' api_json: ", paste(substitute(api_json), collapse = " "),"\n",
    "#' \n",
    "#' Objects for use by the functions created by googleAuthR::gar_create_api_skeleton\n",
    "\n"
  )
  
  add_line(header, temp)
  
  ## take the json and create a file of structures that will get passed to the functions that need them
  object_schema <- api_json$schemas
  set_global(NULL)
  apply_json_props(object_schema)
  properties <- get_global()
  set_global(list())
  
  fd <- lapply(names(properties), object_docs, properties)
  fp <- lapply(names(properties), object_params, properties)
  fb <- lapply(names(properties), object_body, properties)
  
  lapply(paste(fd, fp,fb, sep = "\n\n"), add_line, temp)
  
  formatR::tidy_eval(temp, file = filename, width.cutoff = 80)
  
}


