#' Get a list of Google API libraries
#' 
#' Doesn't require authentication
#' 
#' @seealso \href{https://developers.google.com/discovery/v1/reference/apis/list}
#' 
#' @return List of Google APIs and their resources
#' @export
gar_discovery_apis_list <- function(){
  
  url <- "https://www.googleapis.com/discovery/v1/apis"
  req <- httr::RETRY("GET", url)
  
  httr::stop_for_status(req)
  
  stuff <- httr::content(req, as = "text")
  apis <- jsonlite::fromJSON(stuff)
  
  if(!is.null(apis$kind) && apis$kind == "discovery#directoryList"){
    out <- apis$items
  } else {
    stop("Problem fetching Discovery APIs")
  }
  
  out
}

#' Get meta data details for specified Google API
#' 
#' Doesn't require authentication
#' 
#' @param api The API to fetch
#' @param version The API version to fetch
#' 
#' @seealso \href{https://developers.google.com/discovery/v1/reference/apis/getRest}
#' 
#' @return Details of the API 
#' @export
gar_discovery_api <- function(api, version){
  
  url <- sprintf("https://www.googleapis.com/discovery/v1/apis/%s/%s/rest",
                 api,
                 version)
  
  req <- httr::RETRY("GET", url)
  
  httr::stop_for_status(req)
  
  stuff <- httr::content(req, as = "text")
  api <- jsonlite::fromJSON(stuff)
  
  if(!is.null(api$kind) && api$kind == "discovery#restDescription"){
    out <- api
  } else {
    stop("Problem fetching API Description")
  }
  
  out
}

## from https://github.com/hadley/httr/blob/4624451f8cc395a90730b5a10b50ba005187f2ff/R/oauth-cache.R
add_line <- function(line, path, quiet = FALSE) {
  if (file.exists(path)) {
    lines <- readLines(path, warn = FALSE)
    lines <- lines[lines != ""]
  } else {
    lines <- character()
  }
  
  if (line %in% lines) return(TRUE)
  if (!quiet) message("Adding ", line, " to ", path)
  
  lines <- c(lines, line)
  writeLines(lines, path)
  TRUE
}


#' Create an API library skeleton
#' 
#' This will create a file with the skeleton of the API functions 
#'   for the specified library
#' 
#' @param filename R file to write skeleton to
#' @param api_json The json from \link{gar_discovery_api}
#' 
#' @return TRUE if successful, side effect will write a file
#' @export
gar_create_api_skeleton <- function(filename = "./inst/new_api.R", 
                                    api_json = gar_discovery_api("urlshortener","v1")
                                    ){
  

  if(is.null(api_json$kind) && api_json$kind != "discovery#restDescription"){
    stop("api_json not recognised from gar_discovery_api")
  }
  
  temp <- tempfile()
  
  if(file.exists(filename)){
    stop("File: ", filename, " exists. Delete it and run again")
  }
  
  header <- paste0(
      "#' ", api_json$title, "\n",
      "#' ", api_json$description, "\n",
      "#' \n",
      "#' Auto-generated code by googleAuthR::gar_create_api_skeleton\n",
      "#' filename: ", substitute(filename),"\n",
      "#' api_json: ", paste(substitute(api_json), collapse = " "),"\n",
      "#' \n",
      "#' @details \n",
      "#' Authentication scopes used are:\n",
      "#' \\itemize{\n",
      "#'   \\item ", paste(names(api_json$auth$oauth2$scopes), collapse = "\n#' \\item "),
      "\n#' }\n",
      "#' \n",
      "#' @docType package \n",
      "#' @name ", paste0(api_json$name,"_googleAuthR"), "\n",
      "#' \n",
      "NULL",
      "\n"
      )
  
  add_line(header, temp)
  
  ## apis can have methods at varying steps into JSON tree
  ## find the methods to extract into API
  api_method <- get_json_methods(api_json$resources)
  
  fd <- lapply(api_method, function_docs, api_json = api_json)
  fp <- lapply(api_method, function_params, api_json = api_json)
  fb <- lapply(api_method, function_body, api_json = api_json)

  lapply(paste(fd, fp,fb, sep = "\n\n"), add_line, temp)
  
  formatR::tidy_eval(temp, file = filename, width.cutoff = 80)
  file.remove(temp)
}

function_docs <- function(api_json_resource_method, api_json){
  
  docs <- paste0(
    "\t\n\n",
    "#' ", api_json_resource_method$description, "\n",
    "#' \n",
    "#' Autogenerated via \\code{\\link[googleAuthR]{gar_create_api_skeleton}}\n",
    "#' \n",
    "#' @seealso \\href{",api_json$documentationLink,"}{Google Documentation}\n",
    "#' \n",
    "#' @details \n",
    "#' Authentication scopes used by this function are:\n",
    "#' \\itemize{\n",
    "#'   \\item ", paste(api_json_resource_method$scopes, collapse = "\n#' \\item "),
    "\n#' }\n",
    "#' \n",
    "#' Set \\code{options(googleAuthR.scopes.selected = c(",paste(api_json_resource_method$scopes, collapse = ", "),")}\n",
    "#' Then run \\code{googleAuthR::gar_auth()} to authenticate.\n",
    "#' See \\code{\\link[googleAuthR]{gar_auth}} for details. \n",
    "#' \n",
    "#' ", paste(collapse = "\n#' ", sep = "\n#'",
                 lapply(names(api_json_resource_method$parameters), 
                        make_vars_description, 
                        api_json_resource_method=api_json_resource_method$parameters)
                 ),
    "#' @importFrom googleAuthR gar_api_generator\n",
    "#' @export\n"
  )
  
  docs
}

function_params <- function(api_json_resource_method, api_json){
  
  func <- paste0(
    gsub(paste0(api_json$name,"."), "", api_json_resource_method$id), " <- function(",
    paste(make.names(names(api_json_resource_method$parameters)), sep = "\n", collapse = ",\n"),
    "){\n\n"
  )
  
  func
}

function_body <- function(api_json_resource_method, api_json){
  
  pars_list <- make_pars_list(api_json_resource_method)
  
  api_url <- make_api_url_string(api_json_resource_method, api_json)
    
  fb <- paste0(
    api_url,
    "# ", api_json_resource_method$id,"\n",
    "f <- gar_api_generator(url, \n",
    "'",api_json_resource_method$httpMethod,"',\n",
    pars_list,
    "data_parse_function = function(x) x)\n\n",
    "f()",
    "\n",
    "}\n\n\n"
  )
  
  fb
  
}

make_api_url_string <- function(api_json_resource_method, api_json){
  
  start_url <- paste0(api_json$baseUrl, api_json_resource_method$path)
  path_args <- type_parameters(api_json_resource_method)

  if(length(path_args) > 0){
    ## replace path args with %s
    end_url <- gsub(paste0("\\{(",paste(path_args, collapse = "|"),")\\}"), "%s", start_url)
    out <- paste0("url <- sprintf('", end_url, "'\n,", 
                  paste(make.names(type_parameters(api_json_resource_method)), collapse = ", "),")\n")
  } else {
    out <- paste0("url <- '", start_url, "'\n")
  }

  out
}

## extract names of parameters of type path/query
type_parameters <- function(api_json_resource_method, type = c("path","query")){
  
  type <- match.arg(type)
  pars <- api_json_resource_method$parameters
  
  unlist(lapply(names(pars), function(x) if(pars[[x]]$location == type) x))
  
}

make_pars_list <- function(api_json_resource_method){
  
  query_pars <- type_parameters(api_json_resource_method, "query")
  
  if(length(query_pars) == 0) return(NULL)

  list_vars <- lapply(query_pars, 
                      make_pars_entry,
                      api_json_resource_method = api_json_resource_method)
  paste0(
    "pars_args = list(\n",
    paste(collapse = ",", list_vars),
    "),\n" 
  )
  
}

make_pars_entry <- function(x, api_json_resource_method){
   paste0("\t\t`",x, "` = ", make.names(x), "\n", collapse = "")
}

make_vars_description <- function(x, 
                                 api_json_resource_method){
  
  paste0("@param ", make.names(x), " ", api_json_resource_method[[x]]$description,"\n", 
         collapse = "")
  
}

# get the methods
get_json_methods <- function(api_json_resources){
  
  set_a(list())
  recursive_method_finder(api_json_resources)

}

recursive_method_finder <- function(the_list){

  if("methods" %in% names(the_list)){
    ## success - add to global
    set_a(c(get_a(), the_list$methods))
  } else {
    ## recursive
    lapply(the_list, recursive_method_finder)
  }
  
  get_a()
}

## environment hoops for globals
my_env <- new.env(parent = emptyenv())
my_env$a <- 1

get_a <- function() {
  my_env$a
}
set_a <- function(value) {
  old <- my_env$a
  my_env$a <- value
  invisible(old)
}

#' Create the API objects from the Discovery API
#' 
#' @param filename File to write the objects to
#' @param api_json The json from \link{gar_discovery_api}
#' 
#' @return TRUE if successful, side-effect creating filename
#' @export
create_api_objects <- function(filename = "./inst/api_objects.R", api_json){
  
  ## take the json and create a file of structures that will get passed to the functions that need them
}