#' Turn a list of gar_fetch_functions into batch functions
#' 
#' @description Some Google APIs support batch processing, which dramatically speeds up response 
#'   when you have multiple calls to make.  This function allows you to take advatage of this.
#' 
#' @param a list of functions generated by \code{gar_api_generator}
#' 
#' @return A list of the Google API responses
#' 
#' @seealso \code{\link{https://developers.google.com/webmaster-tools/v3/how-tos/batch}}
#'   Documentation on doing batch requests for the search console API.  
#'   Other Google APIs are similar.
#'   
#' @details This function will turn all the individual Google API functions
#'   into one POST request to /batch. 
#'   
#' @examples
#' \dontrun{
#' # from search console API
#' list_websites <- function() {
#'   l <- gar_api_generator("https://www.googleapis.com/webmasters/v3/sites",
#'                          "GET",
#'                          data_parse_function = function(x) x$siteEntry)
#'   l()
#'   }
#'  
#'  # from goo.gl API
#'  user_history <- function(){
#'    f <- gar_api_generator("https://www.googleapis.com/urlshortener/v1/url/history",
#'                           "GET",
#'                           data_parse_function = function(x) x$items)
#'                           
#'   f()
#'   }
#' 
#' gar_auth()
#' ggg <- gar_batch(list(list_websites(), user_history()))
#' ggg
#' 
#' 
#' } 
#' 
#' @export
#' @family batch functions
gar_batch <- function(call_list){
  
  # function_list <- lapply(call_list, eval)
  function_list <- call_list
  ## construct batch POST request
  parse_list <- lapply(function_list, makeBatchRequest)
  
  parsed <- paste(c(parse_list, "--gar_batch--"), collapse="")
  
  l <- list(parsed = parsed,
            shiny_access_token = function_list[[1]]$shiny_access_token)
  
  ## call doHttrRequest with batched together functions
  req <- doBatchRequest(l)
  batch_content <-  parseBatchResponse(req)
  
  parsed_batch_content <- lapply(function_list, applyDataParseFunction, batch_content)
  message("Batched API request successful")
  parsed_batch_content
  
}

#' Apply parsing function if a good response
#' 
#' @param function_entry a Google API function generated by \code{gar_api_generator}
#' @param the content returned from a batch call
#' 
#' @keywords internal
#' @family batch functions
applyDataParseFunction <- function(function_entry, batch_content){
  
  x <- batch_content[paste0("response",function_entry$name)][[1]]
  
  id <- x$meta[[1]][2]
  status <- x$header[[1]][1]
  content <- x$content[[1]]
 
  ## check that its the right response 
  if(checkGoogleAPIError(content, batched = TRUE)){
    ## apply data parse function from function_list$data_parse_function    
    f <- function_entry$data_parse_function
    contentp <- f(content)
    if(is.null(contentp)){
      warning("Error1: parsing data for:", id, " Returning unparsed content.")
      contentp <- content
    }
    
    contentp
    
  } else {
    warning("Error2: parsing data for:", id, " Returning unparsed content.")
    contentp <- content
  }

  contentp
  
}

#' Parse batch request
#' 
#' @param batch_response An element of the list of responses from a batched request
#' 
#' @keywords internal
#' @family batch functions
parseBatchResponse <- function(batch_response){

  
  b_content <- textConnection(httr::content(batch_response, as="text"))
  r <- readLines(b_content)
  
  index <- which(grepl(r[1], r))
  responses <- split_vector(r, index)
  
  responses_content <- lapply(responses, function(x){
    # index <- which(grepl("^(\\{|\\})$", x))
    index <- which(grepl("Content-Length:", x))
    index <- c(index+1, length(x))
    if(any(is.na(index))){
      warning("Index has an NA. Not splitting JSON")
      return(unlist(split_vector(x, index, remove_splits = FALSE)))
    }
    jsonlite::fromJSON(unlist(split_vector(x, index, remove_splits = FALSE)))
  })
  
  responses_meta <- lapply(responses, function(x){
    index <- c(1:2)
    unlist(split_vector(x, index, remove_splits = FALSE))
  })
  
  responses_header <- lapply(responses, function(x){
    index <- which(grepl("HTTP|Content-Length", x))
    rh <- unlist(split_vector(x, index, remove_splits = FALSE))
    if(grepl("400", rh[2])){
      warning("400 in response")
    }
    rh
    
  })
  

  
  batch_list <- lapply(1:length(responses), 
                       function(x) {
                         list(meta = responses_meta[x], 
                              header = responses_header[x], 
                              content = responses_content[x])
                         })
  names(batch_list) <- gsub("(Content-ID: )|-", "", Reduce(c, lapply(responses_meta, function(x) x[2])))

  
  batch_list
}


#' Make the batch request inner content
#' 
#' @param f The original unbatched Google API function call generated by \code{gar_api_generator}
#' 
#' @keywords internal
#' @family batch functions
makeBatchRequest <- function(f){

  
  boundary <- "--gar_batch"
  url_stem <- gsub("https://www.googleapis.com","",f$req_url)

  message("Constructing batch request URL for: ", url_stem)  
  ## construct batch POST request
  header <- paste(boundary,
                  "Content-Type: application/http",
                  paste0("Content-ID: ",f$name),
                  "\r\n",
                  sep = "\r\n")
  
  content <- paste0(f$http_header," ", 
                    url_stem, "\r\n")
  
  if(!is.null(f$the_body)){
    batch_body <- jsonlite::toJSON(f$the_body)
    part_content_length <- nchar(batch_body)
    header <- paste(c(header, 
                      paste0("Content-Length: ", part_content_length, "\r\n")),
                    collapse = "")
  } else {
    batch_body <- NULL
  }
  
  parsed <- paste(header, content, batch_body, sep = "\r\n")
  
  parsed
  
}

#' Batch Requests
#' 
#' @description
#' Batch requests to Google APIs that support it
#' 
#' @param batched an element of a list of parsed batch requests
#' 
#' @keywords internal
#' @family batch functions
doBatchRequest <- function(batched){
  
  arg_list <- list(config = get_google_token(batched$shiny_access_token), 
                   # url = "http://www.httpbin.org/post", 
                   url = "https://www.googleapis.com/batch", 
                   body = batched$parsed,
                   encode = "multipart",
                   # httr::user_agent("libcurl/7.43.0 r-curl/0.9.3 httr/1.0.0 googleAuthR/0.1.2 (gzip)"),
                   httr::add_headers("Content-Type" = "multipart/mixed; boundary=gar_batch")
                   )
  
  message("Making Batch API call")
  req <- retryRequest(do.call("POST", 
                              args = arg_list,
                              envir = asNamespace("httr")))
  
  req
}